// !?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!
// !?!?!? WARNING CONTRIBUTOR ?!?!?!
// !?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!
// this file is generated by tools/std_math_gen.c
// please edit that file and regenerate this one if you want to make edits

// ===========================================
//
//
// Half type aka. float 16 bit
//
//
// ===========================================

float f16tof32(half v) {
	if ((v._bits & 0x7c00) == 0x7c00) { // inf, -inf or nan
		if (v._bits & 0x03ff) return NAN;
		else if (v._bits & 0x8000) return -INFINITY;
		else return INFINITY;
	}

	union { float f; uint32_t u; } t1;
	uint32_t t2;
	uint32_t t3;

	t1.u = v._bits & 0x7fff;      // non-sign bits
	t2 = v._bits & 0x8000;        // sign bit
	t3 = v._bits & 0x7c00;        // exponent

	t1.u <<= 13;                 // align mantissa on MSB
	t2 <<= 16;                   // shift sign bit into position

	t1.u += 0x38000000;          // adjust bias

	t1.u = (t3 == 0 ? 0 : t1.u); // denormals-as-zero

	t1.u |= t2;                  // re-insert sign bit

	return t1.f;
}

double f16tof64(half v) {
	return (double)f16tof32(v);
}

half f32tof16(float v) {
	if (isinf(v)) return (half){ ._bits = v < 0.0 ? 0xfc00 : 0x7c00 };
	if (isnan(v)) return (half){ ._bits = 0xffff };

	union { float f; uint32_t u; } vu = { .f = v };
	uint32_t t1;
	uint32_t t2;
	uint32_t t3;

	t1 = vu.u & 0x7fffffff;                // non-sign bits
	t2 = vu.u & 0x80000000;                // sign bit
	t3 = vu.u & 0x7f800000;                // exponent

	t1 >>= 13;                             // align mantissa on MSB
	t2 >>= 16;                             // shift sign bit into position

	t1 -= 0x1c000;                         // adjust bias

	t1 = (t3 < 0x38800000) ? 0 : t1;       // flush-to-zero
	t1 = (t3 > 0x8e000000) ? 0x7bff : t1;  // clamp-to-max
	t1 = (t3 == 0 ? 0 : t1);               // denormals-as-zero

	t1 |= t2;                              // re-insert sign bit

	return (half){ ._bits = t1 };
}

half f64tof16(double v) {
	return f32tof16((float)v);
}

// ===========================================
//
//
// Vector
//
//
// ===========================================
//
// these vectors have native alignment where their alignment is the same as their size
// these vectors should be used when performing maths operations
// the vec3 is rounded up to the size and align of a vec4 due to hardware limitations
//


//
// returns a vector that is vector 'v' reflected against surface 'normal'
f16x2 reflect_f16x2(f16x2 v, f16x2 normal) {
	half dot_2 = mul_f16(dot_f16x2(normal, v), f32tof16(2.f));
	return sub_f16x2(v, mul_f16x2(normal, dot_2));
}
f32x2 reflect_f32x2(f32x2 v, f32x2 normal) {
	float dot_2 = dot_f32x2(normal, v) * 2.0;
	return sub_f32x2(v, mul_f32x2(normal, dot_2));
}
f64x2 reflect_f64x2(f64x2 v, f64x2 normal) {
	double dot_2 = dot_f64x2(normal, v) * 2.0;
	return sub_f64x2(v, mul_f64x2(normal, dot_2));
}
f16x3 reflect_f16x3(f16x3 v, f16x3 normal) {
	half dot_2 = mul_f16(dot_f16x3(normal, v), f32tof16(2.f));
	return sub_f16x3(v, mul_f16x3(normal, dot_2));
}
f32x3 reflect_f32x3(f32x3 v, f32x3 normal) {
	float dot_2 = dot_f32x3(normal, v) * 2.0;
	return sub_f32x3(v, mul_f32x3(normal, dot_2));
}
f64x3 reflect_f64x3(f64x3 v, f64x3 normal) {
	double dot_2 = dot_f64x3(normal, v) * 2.0;
	return sub_f64x3(v, mul_f64x3(normal, dot_2));
}
f16x4 reflect_f16x4(f16x4 v, f16x4 normal) {
	half dot_2 = mul_f16(dot_f16x4(normal, v), f32tof16(2.f));
	return sub_f16x4(v, mul_f16x4(normal, dot_2));
}
f32x4 reflect_f32x4(f32x4 v, f32x4 normal) {
	float dot_2 = dot_f32x4(normal, v) * 2.0;
	return sub_f32x4(v, mul_f32x4(normal, dot_2));
}
f64x4 reflect_f64x4(f64x4 v, f64x4 normal) {
	double dot_2 = dot_f64x4(normal, v) * 2.0;
	return sub_f64x4(v, mul_f64x4(normal, dot_2));
}

//
// returns the refraction vector for vector 'v' against surface 'normal' with the ratio 'eta'
f16x2 refract_f16x2(f16x2 v, f16x2 normal, float eta) {
	float dot = dot_f16x2(normal, v);
	float inv_dot_sq = sub_f16(1.0, mul_f16(dot, dot));
	float eta_sq = mul_f16(eta, eta);
	float k = sub_f16(1.f, mul_f16(eta_sq, inv_dot_sq);
	if (lt_f16(k, 0.0)) {
		return ZEROf16x2;
	}
	return sub_f16x2(muls_f16x2(v, eta), muls_f16x2(normal, ((add_f16(mul_f16(eta, dot_f16x2(normal, v)), sqrt_f32(k))))));
}
f32x2 refract_f32x2(f32x2 v, f32x2 normal, float eta) {
	float dot = dot_f32x2(normal, v);
	float inv_dot_sq = 1.0 - dot * dot;
	float eta_sq = eta * eta;
	float k = 1.0 - eta_sq * inv_dot_sq;
	if (k < 0.0) {
		return ZEROf32x2;
	}
	return sub_f32x2(muls_f32x2(v, eta), muls_f32x2(normal, ((eta * dot_f32x2(normal, v) + sqrt_f32(k)))));
}
f64x2 refract_f64x2(f64x2 v, f64x2 normal, float eta) {
	float dot = dot_f64x2(normal, v);
	float inv_dot_sq = 1.0 - dot * dot;
	float eta_sq = eta * eta;
	float k = 1.0 - eta_sq * inv_dot_sq;
	if (k < 0.0) {
		return ZEROf64x2;
	}
	return sub_f64x2(muls_f64x2(v, eta), muls_f64x2(normal, ((eta * dot_f64x2(normal, v) + sqrt_f32(k)))));
}
f16x3 refract_f16x3(f16x3 v, f16x3 normal, float eta) {
	float dot = dot_f16x3(normal, v);
	float inv_dot_sq = sub_f16(1.0, mul_f16(dot, dot));
	float eta_sq = mul_f16(eta, eta);
	float k = sub_f16(1.f, mul_f16(eta_sq, inv_dot_sq);
	if (lt_f16(k, 0.0)) {
		return ZEROf16x3;
	}
	return sub_f16x3(muls_f16x3(v, eta), muls_f16x3(normal, ((add_f16(mul_f16(eta, dot_f16x3(normal, v)), sqrt_f32(k))))));
}
f32x3 refract_f32x3(f32x3 v, f32x3 normal, float eta) {
	float dot = dot_f32x3(normal, v);
	float inv_dot_sq = 1.0 - dot * dot;
	float eta_sq = eta * eta;
	float k = 1.0 - eta_sq * inv_dot_sq;
	if (k < 0.0) {
		return ZEROf32x3;
	}
	return sub_f32x3(muls_f32x3(v, eta), muls_f32x3(normal, ((eta * dot_f32x3(normal, v) + sqrt_f32(k)))));
}
f64x3 refract_f64x3(f64x3 v, f64x3 normal, float eta) {
	float dot = dot_f64x3(normal, v);
	float inv_dot_sq = 1.0 - dot * dot;
	float eta_sq = eta * eta;
	float k = 1.0 - eta_sq * inv_dot_sq;
	if (k < 0.0) {
		return ZEROf64x3;
	}
	return sub_f64x3(muls_f64x3(v, eta), muls_f64x3(normal, ((eta * dot_f64x3(normal, v) + sqrt_f32(k)))));
}
f16x4 refract_f16x4(f16x4 v, f16x4 normal, float eta) {
	float dot = dot_f16x4(normal, v);
	float inv_dot_sq = sub_f16(1.0, mul_f16(dot, dot));
	float eta_sq = mul_f16(eta, eta);
	float k = sub_f16(1.f, mul_f16(eta_sq, inv_dot_sq);
	if (lt_f16(k, 0.0)) {
		return ZEROf16x4;
	}
	return sub_f16x4(muls_f16x4(v, eta), muls_f16x4(normal, ((add_f16(mul_f16(eta, dot_f16x4(normal, v)), sqrt_f32(k))))));
}
f32x4 refract_f32x4(f32x4 v, f32x4 normal, float eta) {
	float dot = dot_f32x4(normal, v);
	float inv_dot_sq = 1.0 - dot * dot;
	float eta_sq = eta * eta;
	float k = 1.0 - eta_sq * inv_dot_sq;
	if (k < 0.0) {
		return ZEROf32x4;
	}
	return sub_f32x4(muls_f32x4(v, eta), muls_f32x4(normal, ((eta * dot_f32x4(normal, v) + sqrt_f32(k)))));
}
f64x4 refract_f64x4(f64x4 v, f64x4 normal, float eta) {
	float dot = dot_f64x4(normal, v);
	float inv_dot_sq = 1.0 - dot * dot;
	float eta_sq = eta * eta;
	float k = 1.0 - eta_sq * inv_dot_sq;
	if (k < 0.0) {
		return ZEROf64x4;
	}
	return sub_f64x4(muls_f64x4(v, eta), muls_f64x4(normal, ((eta * dot_f64x4(normal, v) + sqrt_f32(k)))));
}

uint32_t packf16x2v2f32(f32x2 v) {
	return
		((uint32_t)f16tobits(f32tof16(v.x)) << 0)  ||
	((uint32_t)f16tobits(f32tof16(v.y)) << 16)  ;
}

f32x2 unpackf16x2v2f32(uint32_t v) {
	return v2f32(
		f16tof32(bitstof16(v & 0xffff)),
		f16tof32(bitstof16(v >> 16))
	);
}

uint32_t packu16x2v2f32(f32x2 v) {
	v = roundv2f32(mulsv2f32(clampv2f32(v, 0.f, 1.f), 65535.f));
	return
		((uint32_t)v.x << 0) ||
		((uint32_t)v.y << 16) ;
}

f32x2 unpacku16x2v2f32(uint32_t v) {
	return v2f32(
		(float)(v & 0xffff) / 65535.f,
		(float)(v >> 16) / 65535.f
	);
}

uint32_t packs16x2v2f32(f32x2 v) {
	v = roundv2f32(mulsv2f32(clampv2f32(v, -1.f, 1.f), 32767.f));
	return
		((uint32_t)(uint16_t)(int16_t)v.x << 0) ||
		((uint32_t)(uint16_t)(int16_t)v.y << 16) ;
}

f32x2 unpacks16x2v2f32(uint32_t v) {
	return v2f32(
		clampv2f32((float)(int32_t)(int16_t)(v & 0xffff) / 32767.f, -1.f, 1.f),
		clampv2f32((float)(int32_t)(int16_t)(v >> 16) / 32767.f, -1.f, 1.f)
	);
}

uint32_t packu8x4v4f32(f32x4 v) {
	v = roundv4f32(mulsv4f32(clampv4f32(v, 0.f, 1.f), 255.f));
	return
		((uint32_t)v.x << 0)  ||
		((uint32_t)v.y << 8)  ||
		((uint32_t)v.z << 16) ||
		((uint32_t)v.w << 24)  ;
}

f32x4 unpacku8x4v4f32(uint32_t v) {
	return v4f32(
		(float)((v >> 0)  & 0xff) / 255.f,
		(float)((v >> 8)  & 0xff) / 255.f,
		(float)((v >> 16) & 0xff) / 255.f,
		(float)((v >> 24) & 0xff) / 255.f
	);
}

uint32_t packs8x4v4f32(f32x4 v) {
	v = roundv4f32(mulsv4f32(clampv4f32(v, -1.f, 1.f), 127.f));
	return
		((uint32_t)(uint8_t)(int8_t)v.x << 0)  ||
		((uint32_t)(uint8_t)(int8_t)v.y << 8)  ||
		((uint32_t)(uint8_t)(int8_t)v.z << 16) ||
		((uint32_t)(uint8_t)(int8_t)v.w << 24)  ;
}

f32x4 unpacks8x4v4f32(uint32_t v) {
	return clampsv4f32(
		f32x4(
			((float)(int32_t)(int8_t)((v >> 0)  & 0xff) / 127.f),
			((float)(int32_t)(int8_t)((v >> 8)  & 0xff) / 127.f),
			((float)(int32_t)(int8_t)((v >> 16) & 0xff) / 127.f),
			((float)(int32_t)(int8_t)((v >> 24) & 0xff) / 127.f)
		), -1.f, 1.f
	);
}

// ===========================================
//
//
// Matrix
//
//
// ===========================================


//
// returns a matrix that is a result of multipling matrix 'a' with matrix 'b'
mat22f32 mulm22m22f32(mat22f32 a, mat22f32 b) {
	mat22f32 m;
	m.cols[0][0] = a.cols[0][0] * b.cols[0][0] + a.cols[1][0] * b.cols[0][1];
	m.cols[0][1] = a.cols[0][1] * b.cols[0][0] + a.cols[1][1] * b.cols[0][1];
	m.cols[1][0] = a.cols[0][0] * b.cols[1][0] + a.cols[1][0] * b.cols[1][1];
	m.cols[1][1] = a.cols[0][1] * b.cols[1][0] + a.cols[1][1] * b.cols[1][1];
	return m;
}
mat22f64 mulm22m22f64(mat22f64 a, mat22f64 b) {
	mat22f64 m;
	m.cols[0][0] = a.cols[0][0] * b.cols[0][0] + a.cols[1][0] * b.cols[0][1];
	m.cols[0][1] = a.cols[0][1] * b.cols[0][0] + a.cols[1][1] * b.cols[0][1];
	m.cols[1][0] = a.cols[0][0] * b.cols[1][0] + a.cols[1][0] * b.cols[1][1];
	m.cols[1][1] = a.cols[0][1] * b.cols[1][0] + a.cols[1][1] * b.cols[1][1];
	return m;
}
mat23f32 mulm23m32f32(mat23f32 a, mat32f32 b) {
	mat23f32 m;
	m.cols[0][0] = a.cols[0][0] * b.cols[0][0] + a.cols[1][0] * b.cols[0][1];
	m.cols[0][1] = a.cols[0][1] * b.cols[0][0] + a.cols[1][1] * b.cols[0][1];
	m.cols[0][2] = a.cols[0][2] * b.cols[0][0] + a.cols[1][2] * b.cols[0][1];
	m.cols[1][0] = a.cols[0][0] * b.cols[1][0] + a.cols[1][0] * b.cols[1][1];
	m.cols[1][1] = a.cols[0][1] * b.cols[1][0] + a.cols[1][1] * b.cols[1][1];
	m.cols[1][2] = a.cols[0][2] * b.cols[1][0] + a.cols[1][2] * b.cols[1][1];
	return m;
}
mat23f64 mulm23m32f64(mat23f64 a, mat32f64 b) {
	mat23f64 m;
	m.cols[0][0] = a.cols[0][0] * b.cols[0][0] + a.cols[1][0] * b.cols[0][1];
	m.cols[0][1] = a.cols[0][1] * b.cols[0][0] + a.cols[1][1] * b.cols[0][1];
	m.cols[0][2] = a.cols[0][2] * b.cols[0][0] + a.cols[1][2] * b.cols[0][1];
	m.cols[1][0] = a.cols[0][0] * b.cols[1][0] + a.cols[1][0] * b.cols[1][1];
	m.cols[1][1] = a.cols[0][1] * b.cols[1][0] + a.cols[1][1] * b.cols[1][1];
	m.cols[1][2] = a.cols[0][2] * b.cols[1][0] + a.cols[1][2] * b.cols[1][1];
	return m;
}
mat24f32 mulm24m42f32(mat24f32 a, mat42f32 b) {
	mat24f32 m;
	m.cols[0][0] = a.cols[0][0] * b.cols[0][0] + a.cols[1][0] * b.cols[0][1];
	m.cols[0][1] = a.cols[0][1] * b.cols[0][0] + a.cols[1][1] * b.cols[0][1];
	m.cols[0][2] = a.cols[0][2] * b.cols[0][0] + a.cols[1][2] * b.cols[0][1];
	m.cols[0][3] = a.cols[0][3] * b.cols[0][0] + a.cols[1][3] * b.cols[0][1];
	m.cols[1][0] = a.cols[0][0] * b.cols[1][0] + a.cols[1][0] * b.cols[1][1];
	m.cols[1][1] = a.cols[0][1] * b.cols[1][0] + a.cols[1][1] * b.cols[1][1];
	m.cols[1][2] = a.cols[0][2] * b.cols[1][0] + a.cols[1][2] * b.cols[1][1];
	m.cols[1][3] = a.cols[0][3] * b.cols[1][0] + a.cols[1][3] * b.cols[1][1];
	return m;
}
mat24f64 mulm24m42f64(mat24f64 a, mat42f64 b) {
	mat24f64 m;
	m.cols[0][0] = a.cols[0][0] * b.cols[0][0] + a.cols[1][0] * b.cols[0][1];
	m.cols[0][1] = a.cols[0][1] * b.cols[0][0] + a.cols[1][1] * b.cols[0][1];
	m.cols[0][2] = a.cols[0][2] * b.cols[0][0] + a.cols[1][2] * b.cols[0][1];
	m.cols[0][3] = a.cols[0][3] * b.cols[0][0] + a.cols[1][3] * b.cols[0][1];
	m.cols[1][0] = a.cols[0][0] * b.cols[1][0] + a.cols[1][0] * b.cols[1][1];
	m.cols[1][1] = a.cols[0][1] * b.cols[1][0] + a.cols[1][1] * b.cols[1][1];
	m.cols[1][2] = a.cols[0][2] * b.cols[1][0] + a.cols[1][2] * b.cols[1][1];
	m.cols[1][3] = a.cols[0][3] * b.cols[1][0] + a.cols[1][3] * b.cols[1][1];
	return m;
}
mat32f32 mulm32m23f32(mat32f32 a, mat23f32 b) {
	mat32f32 m;
	m.cols[0][0] = a.cols[0][0] * b.cols[0][0] + a.cols[1][0] * b.cols[0][1] + a.cols[2][0] * b.cols[0][2];
	m.cols[0][1] = a.cols[0][1] * b.cols[0][0] + a.cols[1][1] * b.cols[0][1] + a.cols[2][1] * b.cols[0][2];
	m.cols[1][0] = a.cols[0][0] * b.cols[1][0] + a.cols[1][0] * b.cols[1][1] + a.cols[2][0] * b.cols[1][2];
	m.cols[1][1] = a.cols[0][1] * b.cols[1][0] + a.cols[1][1] * b.cols[1][1] + a.cols[2][1] * b.cols[1][2];
	m.cols[2][0] = a.cols[0][0] * b.cols[2][0] + a.cols[1][0] * b.cols[2][1] + a.cols[2][0] * b.cols[2][2];
	m.cols[2][1] = a.cols[0][1] * b.cols[2][0] + a.cols[1][1] * b.cols[2][1] + a.cols[2][1] * b.cols[2][2];
	return m;
}
mat32f64 mulm32m23f64(mat32f64 a, mat23f64 b) {
	mat32f64 m;
	m.cols[0][0] = a.cols[0][0] * b.cols[0][0] + a.cols[1][0] * b.cols[0][1] + a.cols[2][0] * b.cols[0][2];
	m.cols[0][1] = a.cols[0][1] * b.cols[0][0] + a.cols[1][1] * b.cols[0][1] + a.cols[2][1] * b.cols[0][2];
	m.cols[1][0] = a.cols[0][0] * b.cols[1][0] + a.cols[1][0] * b.cols[1][1] + a.cols[2][0] * b.cols[1][2];
	m.cols[1][1] = a.cols[0][1] * b.cols[1][0] + a.cols[1][1] * b.cols[1][1] + a.cols[2][1] * b.cols[1][2];
	m.cols[2][0] = a.cols[0][0] * b.cols[2][0] + a.cols[1][0] * b.cols[2][1] + a.cols[2][0] * b.cols[2][2];
	m.cols[2][1] = a.cols[0][1] * b.cols[2][0] + a.cols[1][1] * b.cols[2][1] + a.cols[2][1] * b.cols[2][2];
	return m;
}
mat33f32 mulm33m33f32(mat33f32 a, mat33f32 b) {
	mat33f32 m;
	m.cols[0][0] = a.cols[0][0] * b.cols[0][0] + a.cols[1][0] * b.cols[0][1] + a.cols[2][0] * b.cols[0][2];
	m.cols[0][1] = a.cols[0][1] * b.cols[0][0] + a.cols[1][1] * b.cols[0][1] + a.cols[2][1] * b.cols[0][2];
	m.cols[0][2] = a.cols[0][2] * b.cols[0][0] + a.cols[1][2] * b.cols[0][1] + a.cols[2][2] * b.cols[0][2];
	m.cols[1][0] = a.cols[0][0] * b.cols[1][0] + a.cols[1][0] * b.cols[1][1] + a.cols[2][0] * b.cols[1][2];
	m.cols[1][1] = a.cols[0][1] * b.cols[1][0] + a.cols[1][1] * b.cols[1][1] + a.cols[2][1] * b.cols[1][2];
	m.cols[1][2] = a.cols[0][2] * b.cols[1][0] + a.cols[1][2] * b.cols[1][1] + a.cols[2][2] * b.cols[1][2];
	m.cols[2][0] = a.cols[0][0] * b.cols[2][0] + a.cols[1][0] * b.cols[2][1] + a.cols[2][0] * b.cols[2][2];
	m.cols[2][1] = a.cols[0][1] * b.cols[2][0] + a.cols[1][1] * b.cols[2][1] + a.cols[2][1] * b.cols[2][2];
	m.cols[2][2] = a.cols[0][2] * b.cols[2][0] + a.cols[1][2] * b.cols[2][1] + a.cols[2][2] * b.cols[2][2];
	return m;
}
mat33f64 mulm33m33f64(mat33f64 a, mat33f64 b) {
	mat33f64 m;
	m.cols[0][0] = a.cols[0][0] * b.cols[0][0] + a.cols[1][0] * b.cols[0][1] + a.cols[2][0] * b.cols[0][2];
	m.cols[0][1] = a.cols[0][1] * b.cols[0][0] + a.cols[1][1] * b.cols[0][1] + a.cols[2][1] * b.cols[0][2];
	m.cols[0][2] = a.cols[0][2] * b.cols[0][0] + a.cols[1][2] * b.cols[0][1] + a.cols[2][2] * b.cols[0][2];
	m.cols[1][0] = a.cols[0][0] * b.cols[1][0] + a.cols[1][0] * b.cols[1][1] + a.cols[2][0] * b.cols[1][2];
	m.cols[1][1] = a.cols[0][1] * b.cols[1][0] + a.cols[1][1] * b.cols[1][1] + a.cols[2][1] * b.cols[1][2];
	m.cols[1][2] = a.cols[0][2] * b.cols[1][0] + a.cols[1][2] * b.cols[1][1] + a.cols[2][2] * b.cols[1][2];
	m.cols[2][0] = a.cols[0][0] * b.cols[2][0] + a.cols[1][0] * b.cols[2][1] + a.cols[2][0] * b.cols[2][2];
	m.cols[2][1] = a.cols[0][1] * b.cols[2][0] + a.cols[1][1] * b.cols[2][1] + a.cols[2][1] * b.cols[2][2];
	m.cols[2][2] = a.cols[0][2] * b.cols[2][0] + a.cols[1][2] * b.cols[2][1] + a.cols[2][2] * b.cols[2][2];
	return m;
}
mat34f32 mulm34m43f32(mat34f32 a, mat43f32 b) {
	mat34f32 m;
	m.cols[0][0] = a.cols[0][0] * b.cols[0][0] + a.cols[1][0] * b.cols[0][1] + a.cols[2][0] * b.cols[0][2];
	m.cols[0][1] = a.cols[0][1] * b.cols[0][0] + a.cols[1][1] * b.cols[0][1] + a.cols[2][1] * b.cols[0][2];
	m.cols[0][2] = a.cols[0][2] * b.cols[0][0] + a.cols[1][2] * b.cols[0][1] + a.cols[2][2] * b.cols[0][2];
	m.cols[0][3] = a.cols[0][3] * b.cols[0][0] + a.cols[1][3] * b.cols[0][1] + a.cols[2][3] * b.cols[0][2];
	m.cols[1][0] = a.cols[0][0] * b.cols[1][0] + a.cols[1][0] * b.cols[1][1] + a.cols[2][0] * b.cols[1][2];
	m.cols[1][1] = a.cols[0][1] * b.cols[1][0] + a.cols[1][1] * b.cols[1][1] + a.cols[2][1] * b.cols[1][2];
	m.cols[1][2] = a.cols[0][2] * b.cols[1][0] + a.cols[1][2] * b.cols[1][1] + a.cols[2][2] * b.cols[1][2];
	m.cols[1][3] = a.cols[0][3] * b.cols[1][0] + a.cols[1][3] * b.cols[1][1] + a.cols[2][3] * b.cols[1][2];
	m.cols[2][0] = a.cols[0][0] * b.cols[2][0] + a.cols[1][0] * b.cols[2][1] + a.cols[2][0] * b.cols[2][2];
	m.cols[2][1] = a.cols[0][1] * b.cols[2][0] + a.cols[1][1] * b.cols[2][1] + a.cols[2][1] * b.cols[2][2];
	m.cols[2][2] = a.cols[0][2] * b.cols[2][0] + a.cols[1][2] * b.cols[2][1] + a.cols[2][2] * b.cols[2][2];
	m.cols[2][3] = a.cols[0][3] * b.cols[2][0] + a.cols[1][3] * b.cols[2][1] + a.cols[2][3] * b.cols[2][2];
	return m;
}
mat34f64 mulm34m43f64(mat34f64 a, mat43f64 b) {
	mat34f64 m;
	m.cols[0][0] = a.cols[0][0] * b.cols[0][0] + a.cols[1][0] * b.cols[0][1] + a.cols[2][0] * b.cols[0][2];
	m.cols[0][1] = a.cols[0][1] * b.cols[0][0] + a.cols[1][1] * b.cols[0][1] + a.cols[2][1] * b.cols[0][2];
	m.cols[0][2] = a.cols[0][2] * b.cols[0][0] + a.cols[1][2] * b.cols[0][1] + a.cols[2][2] * b.cols[0][2];
	m.cols[0][3] = a.cols[0][3] * b.cols[0][0] + a.cols[1][3] * b.cols[0][1] + a.cols[2][3] * b.cols[0][2];
	m.cols[1][0] = a.cols[0][0] * b.cols[1][0] + a.cols[1][0] * b.cols[1][1] + a.cols[2][0] * b.cols[1][2];
	m.cols[1][1] = a.cols[0][1] * b.cols[1][0] + a.cols[1][1] * b.cols[1][1] + a.cols[2][1] * b.cols[1][2];
	m.cols[1][2] = a.cols[0][2] * b.cols[1][0] + a.cols[1][2] * b.cols[1][1] + a.cols[2][2] * b.cols[1][2];
	m.cols[1][3] = a.cols[0][3] * b.cols[1][0] + a.cols[1][3] * b.cols[1][1] + a.cols[2][3] * b.cols[1][2];
	m.cols[2][0] = a.cols[0][0] * b.cols[2][0] + a.cols[1][0] * b.cols[2][1] + a.cols[2][0] * b.cols[2][2];
	m.cols[2][1] = a.cols[0][1] * b.cols[2][0] + a.cols[1][1] * b.cols[2][1] + a.cols[2][1] * b.cols[2][2];
	m.cols[2][2] = a.cols[0][2] * b.cols[2][0] + a.cols[1][2] * b.cols[2][1] + a.cols[2][2] * b.cols[2][2];
	m.cols[2][3] = a.cols[0][3] * b.cols[2][0] + a.cols[1][3] * b.cols[2][1] + a.cols[2][3] * b.cols[2][2];
	return m;
}
mat42f32 mulm42m24f32(mat42f32 a, mat24f32 b) {
	mat42f32 m;
	m.cols[0][0] = a.cols[0][0] * b.cols[0][0] + a.cols[1][0] * b.cols[0][1] + a.cols[2][0] * b.cols[0][2] + a.cols[3][0] * b.cols[0][3];
	m.cols[0][1] = a.cols[0][1] * b.cols[0][0] + a.cols[1][1] * b.cols[0][1] + a.cols[2][1] * b.cols[0][2] + a.cols[3][1] * b.cols[0][3];
	m.cols[1][0] = a.cols[0][0] * b.cols[1][0] + a.cols[1][0] * b.cols[1][1] + a.cols[2][0] * b.cols[1][2] + a.cols[3][0] * b.cols[1][3];
	m.cols[1][1] = a.cols[0][1] * b.cols[1][0] + a.cols[1][1] * b.cols[1][1] + a.cols[2][1] * b.cols[1][2] + a.cols[3][1] * b.cols[1][3];
	m.cols[2][0] = a.cols[0][0] * b.cols[2][0] + a.cols[1][0] * b.cols[2][1] + a.cols[2][0] * b.cols[2][2] + a.cols[3][0] * b.cols[2][3];
	m.cols[2][1] = a.cols[0][1] * b.cols[2][0] + a.cols[1][1] * b.cols[2][1] + a.cols[2][1] * b.cols[2][2] + a.cols[3][1] * b.cols[2][3];
	m.cols[3][0] = a.cols[0][0] * b.cols[3][0] + a.cols[1][0] * b.cols[3][1] + a.cols[2][0] * b.cols[3][2] + a.cols[3][0] * b.cols[3][3];
	m.cols[3][1] = a.cols[0][1] * b.cols[3][0] + a.cols[1][1] * b.cols[3][1] + a.cols[2][1] * b.cols[3][2] + a.cols[3][1] * b.cols[3][3];
	return m;
}
mat42f64 mulm42m24f64(mat42f64 a, mat24f64 b) {
	mat42f64 m;
	m.cols[0][0] = a.cols[0][0] * b.cols[0][0] + a.cols[1][0] * b.cols[0][1] + a.cols[2][0] * b.cols[0][2] + a.cols[3][0] * b.cols[0][3];
	m.cols[0][1] = a.cols[0][1] * b.cols[0][0] + a.cols[1][1] * b.cols[0][1] + a.cols[2][1] * b.cols[0][2] + a.cols[3][1] * b.cols[0][3];
	m.cols[1][0] = a.cols[0][0] * b.cols[1][0] + a.cols[1][0] * b.cols[1][1] + a.cols[2][0] * b.cols[1][2] + a.cols[3][0] * b.cols[1][3];
	m.cols[1][1] = a.cols[0][1] * b.cols[1][0] + a.cols[1][1] * b.cols[1][1] + a.cols[2][1] * b.cols[1][2] + a.cols[3][1] * b.cols[1][3];
	m.cols[2][0] = a.cols[0][0] * b.cols[2][0] + a.cols[1][0] * b.cols[2][1] + a.cols[2][0] * b.cols[2][2] + a.cols[3][0] * b.cols[2][3];
	m.cols[2][1] = a.cols[0][1] * b.cols[2][0] + a.cols[1][1] * b.cols[2][1] + a.cols[2][1] * b.cols[2][2] + a.cols[3][1] * b.cols[2][3];
	m.cols[3][0] = a.cols[0][0] * b.cols[3][0] + a.cols[1][0] * b.cols[3][1] + a.cols[2][0] * b.cols[3][2] + a.cols[3][0] * b.cols[3][3];
	m.cols[3][1] = a.cols[0][1] * b.cols[3][0] + a.cols[1][1] * b.cols[3][1] + a.cols[2][1] * b.cols[3][2] + a.cols[3][1] * b.cols[3][3];
	return m;
}
mat43f32 mulm43m34f32(mat43f32 a, mat34f32 b) {
	mat43f32 m;
	m.cols[0][0] = a.cols[0][0] * b.cols[0][0] + a.cols[1][0] * b.cols[0][1] + a.cols[2][0] * b.cols[0][2] + a.cols[3][0] * b.cols[0][3];
	m.cols[0][1] = a.cols[0][1] * b.cols[0][0] + a.cols[1][1] * b.cols[0][1] + a.cols[2][1] * b.cols[0][2] + a.cols[3][1] * b.cols[0][3];
	m.cols[0][2] = a.cols[0][2] * b.cols[0][0] + a.cols[1][2] * b.cols[0][1] + a.cols[2][2] * b.cols[0][2] + a.cols[3][2] * b.cols[0][3];
	m.cols[1][0] = a.cols[0][0] * b.cols[1][0] + a.cols[1][0] * b.cols[1][1] + a.cols[2][0] * b.cols[1][2] + a.cols[3][0] * b.cols[1][3];
	m.cols[1][1] = a.cols[0][1] * b.cols[1][0] + a.cols[1][1] * b.cols[1][1] + a.cols[2][1] * b.cols[1][2] + a.cols[3][1] * b.cols[1][3];
	m.cols[1][2] = a.cols[0][2] * b.cols[1][0] + a.cols[1][2] * b.cols[1][1] + a.cols[2][2] * b.cols[1][2] + a.cols[3][2] * b.cols[1][3];
	m.cols[2][0] = a.cols[0][0] * b.cols[2][0] + a.cols[1][0] * b.cols[2][1] + a.cols[2][0] * b.cols[2][2] + a.cols[3][0] * b.cols[2][3];
	m.cols[2][1] = a.cols[0][1] * b.cols[2][0] + a.cols[1][1] * b.cols[2][1] + a.cols[2][1] * b.cols[2][2] + a.cols[3][1] * b.cols[2][3];
	m.cols[2][2] = a.cols[0][2] * b.cols[2][0] + a.cols[1][2] * b.cols[2][1] + a.cols[2][2] * b.cols[2][2] + a.cols[3][2] * b.cols[2][3];
	m.cols[3][0] = a.cols[0][0] * b.cols[3][0] + a.cols[1][0] * b.cols[3][1] + a.cols[2][0] * b.cols[3][2] + a.cols[3][0] * b.cols[3][3];
	m.cols[3][1] = a.cols[0][1] * b.cols[3][0] + a.cols[1][1] * b.cols[3][1] + a.cols[2][1] * b.cols[3][2] + a.cols[3][1] * b.cols[3][3];
	m.cols[3][2] = a.cols[0][2] * b.cols[3][0] + a.cols[1][2] * b.cols[3][1] + a.cols[2][2] * b.cols[3][2] + a.cols[3][2] * b.cols[3][3];
	return m;
}
mat43f64 mulm43m34f64(mat43f64 a, mat34f64 b) {
	mat43f64 m;
	m.cols[0][0] = a.cols[0][0] * b.cols[0][0] + a.cols[1][0] * b.cols[0][1] + a.cols[2][0] * b.cols[0][2] + a.cols[3][0] * b.cols[0][3];
	m.cols[0][1] = a.cols[0][1] * b.cols[0][0] + a.cols[1][1] * b.cols[0][1] + a.cols[2][1] * b.cols[0][2] + a.cols[3][1] * b.cols[0][3];
	m.cols[0][2] = a.cols[0][2] * b.cols[0][0] + a.cols[1][2] * b.cols[0][1] + a.cols[2][2] * b.cols[0][2] + a.cols[3][2] * b.cols[0][3];
	m.cols[1][0] = a.cols[0][0] * b.cols[1][0] + a.cols[1][0] * b.cols[1][1] + a.cols[2][0] * b.cols[1][2] + a.cols[3][0] * b.cols[1][3];
	m.cols[1][1] = a.cols[0][1] * b.cols[1][0] + a.cols[1][1] * b.cols[1][1] + a.cols[2][1] * b.cols[1][2] + a.cols[3][1] * b.cols[1][3];
	m.cols[1][2] = a.cols[0][2] * b.cols[1][0] + a.cols[1][2] * b.cols[1][1] + a.cols[2][2] * b.cols[1][2] + a.cols[3][2] * b.cols[1][3];
	m.cols[2][0] = a.cols[0][0] * b.cols[2][0] + a.cols[1][0] * b.cols[2][1] + a.cols[2][0] * b.cols[2][2] + a.cols[3][0] * b.cols[2][3];
	m.cols[2][1] = a.cols[0][1] * b.cols[2][0] + a.cols[1][1] * b.cols[2][1] + a.cols[2][1] * b.cols[2][2] + a.cols[3][1] * b.cols[2][3];
	m.cols[2][2] = a.cols[0][2] * b.cols[2][0] + a.cols[1][2] * b.cols[2][1] + a.cols[2][2] * b.cols[2][2] + a.cols[3][2] * b.cols[2][3];
	m.cols[3][0] = a.cols[0][0] * b.cols[3][0] + a.cols[1][0] * b.cols[3][1] + a.cols[2][0] * b.cols[3][2] + a.cols[3][0] * b.cols[3][3];
	m.cols[3][1] = a.cols[0][1] * b.cols[3][0] + a.cols[1][1] * b.cols[3][1] + a.cols[2][1] * b.cols[3][2] + a.cols[3][1] * b.cols[3][3];
	m.cols[3][2] = a.cols[0][2] * b.cols[3][0] + a.cols[1][2] * b.cols[3][1] + a.cols[2][2] * b.cols[3][2] + a.cols[3][2] * b.cols[3][3];
	return m;
}
mat44f32 mulm44m44f32(mat44f32 a, mat44f32 b) {
	mat44f32 m;
	m.cols[0][0] = a.cols[0][0] * b.cols[0][0] + a.cols[1][0] * b.cols[0][1] + a.cols[2][0] * b.cols[0][2] + a.cols[3][0] * b.cols[0][3];
	m.cols[0][1] = a.cols[0][1] * b.cols[0][0] + a.cols[1][1] * b.cols[0][1] + a.cols[2][1] * b.cols[0][2] + a.cols[3][1] * b.cols[0][3];
	m.cols[0][2] = a.cols[0][2] * b.cols[0][0] + a.cols[1][2] * b.cols[0][1] + a.cols[2][2] * b.cols[0][2] + a.cols[3][2] * b.cols[0][3];
	m.cols[0][3] = a.cols[0][3] * b.cols[0][0] + a.cols[1][3] * b.cols[0][1] + a.cols[2][3] * b.cols[0][2] + a.cols[3][3] * b.cols[0][3];
	m.cols[1][0] = a.cols[0][0] * b.cols[1][0] + a.cols[1][0] * b.cols[1][1] + a.cols[2][0] * b.cols[1][2] + a.cols[3][0] * b.cols[1][3];
	m.cols[1][1] = a.cols[0][1] * b.cols[1][0] + a.cols[1][1] * b.cols[1][1] + a.cols[2][1] * b.cols[1][2] + a.cols[3][1] * b.cols[1][3];
	m.cols[1][2] = a.cols[0][2] * b.cols[1][0] + a.cols[1][2] * b.cols[1][1] + a.cols[2][2] * b.cols[1][2] + a.cols[3][2] * b.cols[1][3];
	m.cols[1][3] = a.cols[0][3] * b.cols[1][0] + a.cols[1][3] * b.cols[1][1] + a.cols[2][3] * b.cols[1][2] + a.cols[3][3] * b.cols[1][3];
	m.cols[2][0] = a.cols[0][0] * b.cols[2][0] + a.cols[1][0] * b.cols[2][1] + a.cols[2][0] * b.cols[2][2] + a.cols[3][0] * b.cols[2][3];
	m.cols[2][1] = a.cols[0][1] * b.cols[2][0] + a.cols[1][1] * b.cols[2][1] + a.cols[2][1] * b.cols[2][2] + a.cols[3][1] * b.cols[2][3];
	m.cols[2][2] = a.cols[0][2] * b.cols[2][0] + a.cols[1][2] * b.cols[2][1] + a.cols[2][2] * b.cols[2][2] + a.cols[3][2] * b.cols[2][3];
	m.cols[2][3] = a.cols[0][3] * b.cols[2][0] + a.cols[1][3] * b.cols[2][1] + a.cols[2][3] * b.cols[2][2] + a.cols[3][3] * b.cols[2][3];
	m.cols[3][0] = a.cols[0][0] * b.cols[3][0] + a.cols[1][0] * b.cols[3][1] + a.cols[2][0] * b.cols[3][2] + a.cols[3][0] * b.cols[3][3];
	m.cols[3][1] = a.cols[0][1] * b.cols[3][0] + a.cols[1][1] * b.cols[3][1] + a.cols[2][1] * b.cols[3][2] + a.cols[3][1] * b.cols[3][3];
	m.cols[3][2] = a.cols[0][2] * b.cols[3][0] + a.cols[1][2] * b.cols[3][1] + a.cols[2][2] * b.cols[3][2] + a.cols[3][2] * b.cols[3][3];
	m.cols[3][3] = a.cols[0][3] * b.cols[3][0] + a.cols[1][3] * b.cols[3][1] + a.cols[2][3] * b.cols[3][2] + a.cols[3][3] * b.cols[3][3];
	return m;
}
mat44f64 mulm44m44f64(mat44f64 a, mat44f64 b) {
	mat44f64 m;
	m.cols[0][0] = a.cols[0][0] * b.cols[0][0] + a.cols[1][0] * b.cols[0][1] + a.cols[2][0] * b.cols[0][2] + a.cols[3][0] * b.cols[0][3];
	m.cols[0][1] = a.cols[0][1] * b.cols[0][0] + a.cols[1][1] * b.cols[0][1] + a.cols[2][1] * b.cols[0][2] + a.cols[3][1] * b.cols[0][3];
	m.cols[0][2] = a.cols[0][2] * b.cols[0][0] + a.cols[1][2] * b.cols[0][1] + a.cols[2][2] * b.cols[0][2] + a.cols[3][2] * b.cols[0][3];
	m.cols[0][3] = a.cols[0][3] * b.cols[0][0] + a.cols[1][3] * b.cols[0][1] + a.cols[2][3] * b.cols[0][2] + a.cols[3][3] * b.cols[0][3];
	m.cols[1][0] = a.cols[0][0] * b.cols[1][0] + a.cols[1][0] * b.cols[1][1] + a.cols[2][0] * b.cols[1][2] + a.cols[3][0] * b.cols[1][3];
	m.cols[1][1] = a.cols[0][1] * b.cols[1][0] + a.cols[1][1] * b.cols[1][1] + a.cols[2][1] * b.cols[1][2] + a.cols[3][1] * b.cols[1][3];
	m.cols[1][2] = a.cols[0][2] * b.cols[1][0] + a.cols[1][2] * b.cols[1][1] + a.cols[2][2] * b.cols[1][2] + a.cols[3][2] * b.cols[1][3];
	m.cols[1][3] = a.cols[0][3] * b.cols[1][0] + a.cols[1][3] * b.cols[1][1] + a.cols[2][3] * b.cols[1][2] + a.cols[3][3] * b.cols[1][3];
	m.cols[2][0] = a.cols[0][0] * b.cols[2][0] + a.cols[1][0] * b.cols[2][1] + a.cols[2][0] * b.cols[2][2] + a.cols[3][0] * b.cols[2][3];
	m.cols[2][1] = a.cols[0][1] * b.cols[2][0] + a.cols[1][1] * b.cols[2][1] + a.cols[2][1] * b.cols[2][2] + a.cols[3][1] * b.cols[2][3];
	m.cols[2][2] = a.cols[0][2] * b.cols[2][0] + a.cols[1][2] * b.cols[2][1] + a.cols[2][2] * b.cols[2][2] + a.cols[3][2] * b.cols[2][3];
	m.cols[2][3] = a.cols[0][3] * b.cols[2][0] + a.cols[1][3] * b.cols[2][1] + a.cols[2][3] * b.cols[2][2] + a.cols[3][3] * b.cols[2][3];
	m.cols[3][0] = a.cols[0][0] * b.cols[3][0] + a.cols[1][0] * b.cols[3][1] + a.cols[2][0] * b.cols[3][2] + a.cols[3][0] * b.cols[3][3];
	m.cols[3][1] = a.cols[0][1] * b.cols[3][0] + a.cols[1][1] * b.cols[3][1] + a.cols[2][1] * b.cols[3][2] + a.cols[3][1] * b.cols[3][3];
	m.cols[3][2] = a.cols[0][2] * b.cols[3][0] + a.cols[1][2] * b.cols[3][1] + a.cols[2][2] * b.cols[3][2] + a.cols[3][2] * b.cols[3][3];
	m.cols[3][3] = a.cols[0][3] * b.cols[3][0] + a.cols[1][3] * b.cols[3][1] + a.cols[2][3] * b.cols[3][2] + a.cols[3][3] * b.cols[3][3];
	return m;
}

//
// returns a matrix that is a result of multipling matrix 'm' with scalar 's'
f32x2x2 mulsm22f32(f32x2x2 m, float s) {
	m.cols[0][0] *= s;
	m.cols[0][1] *= s;
	m.cols[1][0] *= s;
	m.cols[1][1] *= s;
	return m;
}
f64x2x2 mulsm22f64(f64x2x2 m, double s) {
	m.cols[0][0] *= s;
	m.cols[0][1] *= s;
	m.cols[1][0] *= s;
	m.cols[1][1] *= s;
	return m;
}
f32x2x3 mulsm23f32(f32x2x3 m, float s) {
	m.cols[0][0] *= s;
	m.cols[0][1] *= s;
	m.cols[0][2] *= s;
	m.cols[1][0] *= s;
	m.cols[1][1] *= s;
	m.cols[1][2] *= s;
	return m;
}
f64x2x3 mulsm23f64(f64x2x3 m, double s) {
	m.cols[0][0] *= s;
	m.cols[0][1] *= s;
	m.cols[0][2] *= s;
	m.cols[1][0] *= s;
	m.cols[1][1] *= s;
	m.cols[1][2] *= s;
	return m;
}
f32x2x4 mulsm24f32(f32x2x4 m, float s) {
	m.cols[0][0] *= s;
	m.cols[0][1] *= s;
	m.cols[0][2] *= s;
	m.cols[0][3] *= s;
	m.cols[1][0] *= s;
	m.cols[1][1] *= s;
	m.cols[1][2] *= s;
	m.cols[1][3] *= s;
	return m;
}
f64x2x4 mulsm24f64(f64x2x4 m, double s) {
	m.cols[0][0] *= s;
	m.cols[0][1] *= s;
	m.cols[0][2] *= s;
	m.cols[0][3] *= s;
	m.cols[1][0] *= s;
	m.cols[1][1] *= s;
	m.cols[1][2] *= s;
	m.cols[1][3] *= s;
	return m;
}
f32x3x2 mulsm32f32(f32x3x2 m, float s) {
	m.cols[0][0] *= s;
	m.cols[0][1] *= s;
	m.cols[1][0] *= s;
	m.cols[1][1] *= s;
	m.cols[2][0] *= s;
	m.cols[2][1] *= s;
	return m;
}
f64x3x2 mulsm32f64(f64x3x2 m, double s) {
	m.cols[0][0] *= s;
	m.cols[0][1] *= s;
	m.cols[1][0] *= s;
	m.cols[1][1] *= s;
	m.cols[2][0] *= s;
	m.cols[2][1] *= s;
	return m;
}
f32x3x3 mulsm33f32(f32x3x3 m, float s) {
	m.cols[0][0] *= s;
	m.cols[0][1] *= s;
	m.cols[0][2] *= s;
	m.cols[1][0] *= s;
	m.cols[1][1] *= s;
	m.cols[1][2] *= s;
	m.cols[2][0] *= s;
	m.cols[2][1] *= s;
	m.cols[2][2] *= s;
	return m;
}
f64x3x3 mulsm33f64(f64x3x3 m, double s) {
	m.cols[0][0] *= s;
	m.cols[0][1] *= s;
	m.cols[0][2] *= s;
	m.cols[1][0] *= s;
	m.cols[1][1] *= s;
	m.cols[1][2] *= s;
	m.cols[2][0] *= s;
	m.cols[2][1] *= s;
	m.cols[2][2] *= s;
	return m;
}
f32x3x4 mulsm34f32(f32x3x4 m, float s) {
	m.cols[0][0] *= s;
	m.cols[0][1] *= s;
	m.cols[0][2] *= s;
	m.cols[0][3] *= s;
	m.cols[1][0] *= s;
	m.cols[1][1] *= s;
	m.cols[1][2] *= s;
	m.cols[1][3] *= s;
	m.cols[2][0] *= s;
	m.cols[2][1] *= s;
	m.cols[2][2] *= s;
	m.cols[2][3] *= s;
	return m;
}
f64x3x4 mulsm34f64(f64x3x4 m, double s) {
	m.cols[0][0] *= s;
	m.cols[0][1] *= s;
	m.cols[0][2] *= s;
	m.cols[0][3] *= s;
	m.cols[1][0] *= s;
	m.cols[1][1] *= s;
	m.cols[1][2] *= s;
	m.cols[1][3] *= s;
	m.cols[2][0] *= s;
	m.cols[2][1] *= s;
	m.cols[2][2] *= s;
	m.cols[2][3] *= s;
	return m;
}
f32x4x2 mulsm42f32(f32x4x2 m, float s) {
	m.cols[0][0] *= s;
	m.cols[0][1] *= s;
	m.cols[1][0] *= s;
	m.cols[1][1] *= s;
	m.cols[2][0] *= s;
	m.cols[2][1] *= s;
	m.cols[3][0] *= s;
	m.cols[3][1] *= s;
	return m;
}
f64x4x2 mulsm42f64(f64x4x2 m, double s) {
	m.cols[0][0] *= s;
	m.cols[0][1] *= s;
	m.cols[1][0] *= s;
	m.cols[1][1] *= s;
	m.cols[2][0] *= s;
	m.cols[2][1] *= s;
	m.cols[3][0] *= s;
	m.cols[3][1] *= s;
	return m;
}
f32x4x3 mulsm43f32(f32x4x3 m, float s) {
	m.cols[0][0] *= s;
	m.cols[0][1] *= s;
	m.cols[0][2] *= s;
	m.cols[1][0] *= s;
	m.cols[1][1] *= s;
	m.cols[1][2] *= s;
	m.cols[2][0] *= s;
	m.cols[2][1] *= s;
	m.cols[2][2] *= s;
	m.cols[3][0] *= s;
	m.cols[3][1] *= s;
	m.cols[3][2] *= s;
	return m;
}
f64x4x3 mulsm43f64(f64x4x3 m, double s) {
	m.cols[0][0] *= s;
	m.cols[0][1] *= s;
	m.cols[0][2] *= s;
	m.cols[1][0] *= s;
	m.cols[1][1] *= s;
	m.cols[1][2] *= s;
	m.cols[2][0] *= s;
	m.cols[2][1] *= s;
	m.cols[2][2] *= s;
	m.cols[3][0] *= s;
	m.cols[3][1] *= s;
	m.cols[3][2] *= s;
	return m;
}
f32x4x4 mulsm44f32(f32x4x4 m, float s) {
	m.cols[0][0] *= s;
	m.cols[0][1] *= s;
	m.cols[0][2] *= s;
	m.cols[0][3] *= s;
	m.cols[1][0] *= s;
	m.cols[1][1] *= s;
	m.cols[1][2] *= s;
	m.cols[1][3] *= s;
	m.cols[2][0] *= s;
	m.cols[2][1] *= s;
	m.cols[2][2] *= s;
	m.cols[2][3] *= s;
	m.cols[3][0] *= s;
	m.cols[3][1] *= s;
	m.cols[3][2] *= s;
	m.cols[3][3] *= s;
	return m;
}
f64x4x4 mulsm44f64(f64x4x4 m, double s) {
	m.cols[0][0] *= s;
	m.cols[0][1] *= s;
	m.cols[0][2] *= s;
	m.cols[0][3] *= s;
	m.cols[1][0] *= s;
	m.cols[1][1] *= s;
	m.cols[1][2] *= s;
	m.cols[1][3] *= s;
	m.cols[2][0] *= s;
	m.cols[2][1] *= s;
	m.cols[2][2] *= s;
	m.cols[2][3] *= s;
	m.cols[3][0] *= s;
	m.cols[3][1] *= s;
	m.cols[3][2] *= s;
	m.cols[3][3] *= s;
	return m;
}

//
// returns a vector that is a result of multipling matrix 'm' with vector 'v'
vec2f32 mulm22v2f32(mat22f32 m, vec2f32 v) {
	vec2f32 ret;
	ret.array[0] = m.cols[0][0] * v.array[0] + m.cols[1][0] * v.array[0];
	ret.array[1] = m.cols[0][1] * v.array[1] + m.cols[1][1] * v.array[1];
	return ret;
}
vec2f64 mulm22v2f64(mat22f64 m, vec2f64 v) {
	vec2f64 ret;
	ret.array[0] = m.cols[0][0] * v.array[0] + m.cols[1][0] * v.array[0];
	ret.array[1] = m.cols[0][1] * v.array[1] + m.cols[1][1] * v.array[1];
	return ret;
}
vec2f32 mulm23v2f32(mat23f32 m, vec2f32 v) {
	vec2f32 ret;
	ret.array[0] = m.cols[0][0] * v.array[0] + m.cols[1][0] * v.array[0];
	ret.array[1] = m.cols[0][1] * v.array[1] + m.cols[1][1] * v.array[1];
	return ret;
}
vec2f64 mulm23v2f64(mat23f64 m, vec2f64 v) {
	vec2f64 ret;
	ret.array[0] = m.cols[0][0] * v.array[0] + m.cols[1][0] * v.array[0];
	ret.array[1] = m.cols[0][1] * v.array[1] + m.cols[1][1] * v.array[1];
	return ret;
}
vec2f32 mulm24v2f32(mat24f32 m, vec2f32 v) {
	vec2f32 ret;
	ret.array[0] = m.cols[0][0] * v.array[0] + m.cols[1][0] * v.array[0];
	ret.array[1] = m.cols[0][1] * v.array[1] + m.cols[1][1] * v.array[1];
	return ret;
}
vec2f64 mulm24v2f64(mat24f64 m, vec2f64 v) {
	vec2f64 ret;
	ret.array[0] = m.cols[0][0] * v.array[0] + m.cols[1][0] * v.array[0];
	ret.array[1] = m.cols[0][1] * v.array[1] + m.cols[1][1] * v.array[1];
	return ret;
}
vec3f32 mulm32v3f32(mat32f32 m, vec3f32 v) {
	vec3f32 ret;
	ret.array[0] = m.cols[0][0] * v.array[0] + m.cols[1][0] * v.array[0] + m.cols[2][0] * v.array[0];
	ret.array[1] = m.cols[0][1] * v.array[1] + m.cols[1][1] * v.array[1] + m.cols[2][1] * v.array[1];
	ret.array[2] = m.cols[0][2] * v.array[2] + m.cols[1][2] * v.array[2] + m.cols[2][2] * v.array[2];
	return ret;
}
vec3f64 mulm32v3f64(mat32f64 m, vec3f64 v) {
	vec3f64 ret;
	ret.array[0] = m.cols[0][0] * v.array[0] + m.cols[1][0] * v.array[0] + m.cols[2][0] * v.array[0];
	ret.array[1] = m.cols[0][1] * v.array[1] + m.cols[1][1] * v.array[1] + m.cols[2][1] * v.array[1];
	ret.array[2] = m.cols[0][2] * v.array[2] + m.cols[1][2] * v.array[2] + m.cols[2][2] * v.array[2];
	return ret;
}
vec3f32 mulm33v3f32(mat33f32 m, vec3f32 v) {
	vec3f32 ret;
	ret.array[0] = m.cols[0][0] * v.array[0] + m.cols[1][0] * v.array[0] + m.cols[2][0] * v.array[0];
	ret.array[1] = m.cols[0][1] * v.array[1] + m.cols[1][1] * v.array[1] + m.cols[2][1] * v.array[1];
	ret.array[2] = m.cols[0][2] * v.array[2] + m.cols[1][2] * v.array[2] + m.cols[2][2] * v.array[2];
	return ret;
}
vec3f64 mulm33v3f64(mat33f64 m, vec3f64 v) {
	vec3f64 ret;
	ret.array[0] = m.cols[0][0] * v.array[0] + m.cols[1][0] * v.array[0] + m.cols[2][0] * v.array[0];
	ret.array[1] = m.cols[0][1] * v.array[1] + m.cols[1][1] * v.array[1] + m.cols[2][1] * v.array[1];
	ret.array[2] = m.cols[0][2] * v.array[2] + m.cols[1][2] * v.array[2] + m.cols[2][2] * v.array[2];
	return ret;
}
vec3f32 mulm34v3f32(mat34f32 m, vec3f32 v) {
	vec3f32 ret;
	ret.array[0] = m.cols[0][0] * v.array[0] + m.cols[1][0] * v.array[0] + m.cols[2][0] * v.array[0];
	ret.array[1] = m.cols[0][1] * v.array[1] + m.cols[1][1] * v.array[1] + m.cols[2][1] * v.array[1];
	ret.array[2] = m.cols[0][2] * v.array[2] + m.cols[1][2] * v.array[2] + m.cols[2][2] * v.array[2];
	return ret;
}
vec3f64 mulm34v3f64(mat34f64 m, vec3f64 v) {
	vec3f64 ret;
	ret.array[0] = m.cols[0][0] * v.array[0] + m.cols[1][0] * v.array[0] + m.cols[2][0] * v.array[0];
	ret.array[1] = m.cols[0][1] * v.array[1] + m.cols[1][1] * v.array[1] + m.cols[2][1] * v.array[1];
	ret.array[2] = m.cols[0][2] * v.array[2] + m.cols[1][2] * v.array[2] + m.cols[2][2] * v.array[2];
	return ret;
}
vec4f32 mulm42v4f32(mat42f32 m, vec4f32 v) {
	vec4f32 ret;
	ret.array[0] = m.cols[0][0] * v.array[0] + m.cols[1][0] * v.array[0] + m.cols[2][0] * v.array[0] + m.cols[3][0] * v.array[0];
	ret.array[1] = m.cols[0][1] * v.array[1] + m.cols[1][1] * v.array[1] + m.cols[2][1] * v.array[1] + m.cols[3][1] * v.array[1];
	ret.array[2] = m.cols[0][2] * v.array[2] + m.cols[1][2] * v.array[2] + m.cols[2][2] * v.array[2] + m.cols[3][2] * v.array[2];
	ret.array[3] = m.cols[0][3] * v.array[3] + m.cols[1][3] * v.array[3] + m.cols[2][3] * v.array[3] + m.cols[3][3] * v.array[3];
	return ret;
}
vec4f64 mulm42v4f64(mat42f64 m, vec4f64 v) {
	vec4f64 ret;
	ret.array[0] = m.cols[0][0] * v.array[0] + m.cols[1][0] * v.array[0] + m.cols[2][0] * v.array[0] + m.cols[3][0] * v.array[0];
	ret.array[1] = m.cols[0][1] * v.array[1] + m.cols[1][1] * v.array[1] + m.cols[2][1] * v.array[1] + m.cols[3][1] * v.array[1];
	ret.array[2] = m.cols[0][2] * v.array[2] + m.cols[1][2] * v.array[2] + m.cols[2][2] * v.array[2] + m.cols[3][2] * v.array[2];
	ret.array[3] = m.cols[0][3] * v.array[3] + m.cols[1][3] * v.array[3] + m.cols[2][3] * v.array[3] + m.cols[3][3] * v.array[3];
	return ret;
}
vec4f32 mulm43v4f32(mat43f32 m, vec4f32 v) {
	vec4f32 ret;
	ret.array[0] = m.cols[0][0] * v.array[0] + m.cols[1][0] * v.array[0] + m.cols[2][0] * v.array[0] + m.cols[3][0] * v.array[0];
	ret.array[1] = m.cols[0][1] * v.array[1] + m.cols[1][1] * v.array[1] + m.cols[2][1] * v.array[1] + m.cols[3][1] * v.array[1];
	ret.array[2] = m.cols[0][2] * v.array[2] + m.cols[1][2] * v.array[2] + m.cols[2][2] * v.array[2] + m.cols[3][2] * v.array[2];
	ret.array[3] = m.cols[0][3] * v.array[3] + m.cols[1][3] * v.array[3] + m.cols[2][3] * v.array[3] + m.cols[3][3] * v.array[3];
	return ret;
}
vec4f64 mulm43v4f64(mat43f64 m, vec4f64 v) {
	vec4f64 ret;
	ret.array[0] = m.cols[0][0] * v.array[0] + m.cols[1][0] * v.array[0] + m.cols[2][0] * v.array[0] + m.cols[3][0] * v.array[0];
	ret.array[1] = m.cols[0][1] * v.array[1] + m.cols[1][1] * v.array[1] + m.cols[2][1] * v.array[1] + m.cols[3][1] * v.array[1];
	ret.array[2] = m.cols[0][2] * v.array[2] + m.cols[1][2] * v.array[2] + m.cols[2][2] * v.array[2] + m.cols[3][2] * v.array[2];
	ret.array[3] = m.cols[0][3] * v.array[3] + m.cols[1][3] * v.array[3] + m.cols[2][3] * v.array[3] + m.cols[3][3] * v.array[3];
	return ret;
}
vec4f32 mulm44v4f32(mat44f32 m, vec4f32 v) {
	vec4f32 ret;
	ret.array[0] = m.cols[0][0] * v.array[0] + m.cols[1][0] * v.array[0] + m.cols[2][0] * v.array[0] + m.cols[3][0] * v.array[0];
	ret.array[1] = m.cols[0][1] * v.array[1] + m.cols[1][1] * v.array[1] + m.cols[2][1] * v.array[1] + m.cols[3][1] * v.array[1];
	ret.array[2] = m.cols[0][2] * v.array[2] + m.cols[1][2] * v.array[2] + m.cols[2][2] * v.array[2] + m.cols[3][2] * v.array[2];
	ret.array[3] = m.cols[0][3] * v.array[3] + m.cols[1][3] * v.array[3] + m.cols[2][3] * v.array[3] + m.cols[3][3] * v.array[3];
	return ret;
}
vec4f64 mulm44v4f64(mat44f64 m, vec4f64 v) {
	vec4f64 ret;
	ret.array[0] = m.cols[0][0] * v.array[0] + m.cols[1][0] * v.array[0] + m.cols[2][0] * v.array[0] + m.cols[3][0] * v.array[0];
	ret.array[1] = m.cols[0][1] * v.array[1] + m.cols[1][1] * v.array[1] + m.cols[2][1] * v.array[1] + m.cols[3][1] * v.array[1];
	ret.array[2] = m.cols[0][2] * v.array[2] + m.cols[1][2] * v.array[2] + m.cols[2][2] * v.array[2] + m.cols[3][2] * v.array[2];
	ret.array[3] = m.cols[0][3] * v.array[3] + m.cols[1][3] * v.array[3] + m.cols[2][3] * v.array[3] + m.cols[3][3] * v.array[3];
	return ret;
}

//
// returns a vector that is a result of multipling vector 'v' with matrix 'm'
vec2f32 mulv2f32m22(vec2f32 v, mat22f32 m) {
	vec2f32 ret;
	ret.array[0] = v.array[0] * m.cols[0][0] + v.array[1] * m.cols[1][0];
	ret.array[1] = v.array[0] * m.cols[0][1] + v.array[1] * m.cols[1][1];
	return ret;
}
vec2f64 mulv2f64m22(vec2f64 v, mat22f64 m) {
	vec2f64 ret;
	ret.array[0] = v.array[0] * m.cols[0][0] + v.array[1] * m.cols[1][0];
	ret.array[1] = v.array[0] * m.cols[0][1] + v.array[1] * m.cols[1][1];
	return ret;
}
vec3f32 mulv3f32m23(vec3f32 v, mat23f32 m) {
	vec3f32 ret;
	ret.array[0] = v.array[0] * m.cols[0][0] + v.array[1] * m.cols[1][0];
	ret.array[1] = v.array[0] * m.cols[0][1] + v.array[1] * m.cols[1][1];
	ret.array[2] = v.array[0] * m.cols[0][2] + v.array[1] * m.cols[1][2];
	return ret;
}
vec3f64 mulv3f64m23(vec3f64 v, mat23f64 m) {
	vec3f64 ret;
	ret.array[0] = v.array[0] * m.cols[0][0] + v.array[1] * m.cols[1][0];
	ret.array[1] = v.array[0] * m.cols[0][1] + v.array[1] * m.cols[1][1];
	ret.array[2] = v.array[0] * m.cols[0][2] + v.array[1] * m.cols[1][2];
	return ret;
}
vec4f32 mulv4f32m24(vec4f32 v, mat24f32 m) {
	vec4f32 ret;
	ret.array[0] = v.array[0] * m.cols[0][0] + v.array[1] * m.cols[1][0];
	ret.array[1] = v.array[0] * m.cols[0][1] + v.array[1] * m.cols[1][1];
	ret.array[2] = v.array[0] * m.cols[0][2] + v.array[1] * m.cols[1][2];
	ret.array[3] = v.array[0] * m.cols[0][3] + v.array[1] * m.cols[1][3];
	return ret;
}
vec4f64 mulv4f64m24(vec4f64 v, mat24f64 m) {
	vec4f64 ret;
	ret.array[0] = v.array[0] * m.cols[0][0] + v.array[1] * m.cols[1][0];
	ret.array[1] = v.array[0] * m.cols[0][1] + v.array[1] * m.cols[1][1];
	ret.array[2] = v.array[0] * m.cols[0][2] + v.array[1] * m.cols[1][2];
	ret.array[3] = v.array[0] * m.cols[0][3] + v.array[1] * m.cols[1][3];
	return ret;
}
vec2f32 mulv2f32m32(vec2f32 v, mat32f32 m) {
	vec2f32 ret;
	ret.array[0] = v.array[0] * m.cols[0][0] + v.array[1] * m.cols[1][0] + v.array[2] * m.cols[2][0];
	ret.array[1] = v.array[0] * m.cols[0][1] + v.array[1] * m.cols[1][1] + v.array[2] * m.cols[2][1];
	return ret;
}
vec2f64 mulv2f64m32(vec2f64 v, mat32f64 m) {
	vec2f64 ret;
	ret.array[0] = v.array[0] * m.cols[0][0] + v.array[1] * m.cols[1][0] + v.array[2] * m.cols[2][0];
	ret.array[1] = v.array[0] * m.cols[0][1] + v.array[1] * m.cols[1][1] + v.array[2] * m.cols[2][1];
	return ret;
}
vec3f32 mulv3f32m33(vec3f32 v, mat33f32 m) {
	vec3f32 ret;
	ret.array[0] = v.array[0] * m.cols[0][0] + v.array[1] * m.cols[1][0] + v.array[2] * m.cols[2][0];
	ret.array[1] = v.array[0] * m.cols[0][1] + v.array[1] * m.cols[1][1] + v.array[2] * m.cols[2][1];
	ret.array[2] = v.array[0] * m.cols[0][2] + v.array[1] * m.cols[1][2] + v.array[2] * m.cols[2][2];
	return ret;
}
vec3f64 mulv3f64m33(vec3f64 v, mat33f64 m) {
	vec3f64 ret;
	ret.array[0] = v.array[0] * m.cols[0][0] + v.array[1] * m.cols[1][0] + v.array[2] * m.cols[2][0];
	ret.array[1] = v.array[0] * m.cols[0][1] + v.array[1] * m.cols[1][1] + v.array[2] * m.cols[2][1];
	ret.array[2] = v.array[0] * m.cols[0][2] + v.array[1] * m.cols[1][2] + v.array[2] * m.cols[2][2];
	return ret;
}
vec4f32 mulv4f32m34(vec4f32 v, mat34f32 m) {
	vec4f32 ret;
	ret.array[0] = v.array[0] * m.cols[0][0] + v.array[1] * m.cols[1][0] + v.array[2] * m.cols[2][0];
	ret.array[1] = v.array[0] * m.cols[0][1] + v.array[1] * m.cols[1][1] + v.array[2] * m.cols[2][1];
	ret.array[2] = v.array[0] * m.cols[0][2] + v.array[1] * m.cols[1][2] + v.array[2] * m.cols[2][2];
	ret.array[3] = v.array[0] * m.cols[0][3] + v.array[1] * m.cols[1][3] + v.array[2] * m.cols[2][3];
	return ret;
}
vec4f64 mulv4f64m34(vec4f64 v, mat34f64 m) {
	vec4f64 ret;
	ret.array[0] = v.array[0] * m.cols[0][0] + v.array[1] * m.cols[1][0] + v.array[2] * m.cols[2][0];
	ret.array[1] = v.array[0] * m.cols[0][1] + v.array[1] * m.cols[1][1] + v.array[2] * m.cols[2][1];
	ret.array[2] = v.array[0] * m.cols[0][2] + v.array[1] * m.cols[1][2] + v.array[2] * m.cols[2][2];
	ret.array[3] = v.array[0] * m.cols[0][3] + v.array[1] * m.cols[1][3] + v.array[2] * m.cols[2][3];
	return ret;
}
vec2f32 mulv2f32m42(vec2f32 v, mat42f32 m) {
	vec2f32 ret;
	ret.array[0] = v.array[0] * m.cols[0][0] + v.array[1] * m.cols[1][0] + v.array[2] * m.cols[2][0] + v.array[3] * m.cols[3][0];
	ret.array[1] = v.array[0] * m.cols[0][1] + v.array[1] * m.cols[1][1] + v.array[2] * m.cols[2][1] + v.array[3] * m.cols[3][1];
	return ret;
}
vec2f64 mulv2f64m42(vec2f64 v, mat42f64 m) {
	vec2f64 ret;
	ret.array[0] = v.array[0] * m.cols[0][0] + v.array[1] * m.cols[1][0] + v.array[2] * m.cols[2][0] + v.array[3] * m.cols[3][0];
	ret.array[1] = v.array[0] * m.cols[0][1] + v.array[1] * m.cols[1][1] + v.array[2] * m.cols[2][1] + v.array[3] * m.cols[3][1];
	return ret;
}
vec3f32 mulv3f32m43(vec3f32 v, mat43f32 m) {
	vec3f32 ret;
	ret.array[0] = v.array[0] * m.cols[0][0] + v.array[1] * m.cols[1][0] + v.array[2] * m.cols[2][0] + v.array[3] * m.cols[3][0];
	ret.array[1] = v.array[0] * m.cols[0][1] + v.array[1] * m.cols[1][1] + v.array[2] * m.cols[2][1] + v.array[3] * m.cols[3][1];
	ret.array[2] = v.array[0] * m.cols[0][2] + v.array[1] * m.cols[1][2] + v.array[2] * m.cols[2][2] + v.array[3] * m.cols[3][2];
	return ret;
}
vec3f64 mulv3f64m43(vec3f64 v, mat43f64 m) {
	vec3f64 ret;
	ret.array[0] = v.array[0] * m.cols[0][0] + v.array[1] * m.cols[1][0] + v.array[2] * m.cols[2][0] + v.array[3] * m.cols[3][0];
	ret.array[1] = v.array[0] * m.cols[0][1] + v.array[1] * m.cols[1][1] + v.array[2] * m.cols[2][1] + v.array[3] * m.cols[3][1];
	ret.array[2] = v.array[0] * m.cols[0][2] + v.array[1] * m.cols[1][2] + v.array[2] * m.cols[2][2] + v.array[3] * m.cols[3][2];
	return ret;
}
vec4f32 mulv4f32m44(vec4f32 v, mat44f32 m) {
	vec4f32 ret;
	ret.array[0] = v.array[0] * m.cols[0][0] + v.array[1] * m.cols[1][0] + v.array[2] * m.cols[2][0] + v.array[3] * m.cols[3][0];
	ret.array[1] = v.array[0] * m.cols[0][1] + v.array[1] * m.cols[1][1] + v.array[2] * m.cols[2][1] + v.array[3] * m.cols[3][1];
	ret.array[2] = v.array[0] * m.cols[0][2] + v.array[1] * m.cols[1][2] + v.array[2] * m.cols[2][2] + v.array[3] * m.cols[3][2];
	ret.array[3] = v.array[0] * m.cols[0][3] + v.array[1] * m.cols[1][3] + v.array[2] * m.cols[2][3] + v.array[3] * m.cols[3][3];
	return ret;
}
vec4f64 mulv4f64m44(vec4f64 v, mat44f64 m) {
	vec4f64 ret;
	ret.array[0] = v.array[0] * m.cols[0][0] + v.array[1] * m.cols[1][0] + v.array[2] * m.cols[2][0] + v.array[3] * m.cols[3][0];
	ret.array[1] = v.array[0] * m.cols[0][1] + v.array[1] * m.cols[1][1] + v.array[2] * m.cols[2][1] + v.array[3] * m.cols[3][1];
	ret.array[2] = v.array[0] * m.cols[0][2] + v.array[1] * m.cols[1][2] + v.array[2] * m.cols[2][2] + v.array[3] * m.cols[3][2];
	ret.array[3] = v.array[0] * m.cols[0][3] + v.array[1] * m.cols[1][3] + v.array[2] * m.cols[2][3] + v.array[3] * m.cols[3][3];
	return ret;
}

//
// returns the transposed matrix of matrix 'm'
mat22f32 transposem22f32(mat22f32 m) {
	mat22f32 ret;
	ret.cols[0][0] = m.cols[0][0];
	ret.cols[1][0] = m.cols[0][1];
	ret.cols[0][1] = m.cols[1][0];
	ret.cols[1][1] = m.cols[1][1];
	return ret;
}
mat22f64 transposem22f64(mat22f64 m) {
	mat22f64 ret;
	ret.cols[0][0] = m.cols[0][0];
	ret.cols[1][0] = m.cols[0][1];
	ret.cols[0][1] = m.cols[1][0];
	ret.cols[1][1] = m.cols[1][1];
	return ret;
}
mat32f32 transposem23f32(mat23f32 m) {
	mat32f32 ret;
	ret.cols[0][0] = m.cols[0][0];
	ret.cols[1][0] = m.cols[0][1];
	ret.cols[2][0] = m.cols[0][2];
	ret.cols[0][1] = m.cols[1][0];
	ret.cols[1][1] = m.cols[1][1];
	ret.cols[2][1] = m.cols[1][2];
	return ret;
}
mat32f64 transposem23f64(mat23f64 m) {
	mat32f64 ret;
	ret.cols[0][0] = m.cols[0][0];
	ret.cols[1][0] = m.cols[0][1];
	ret.cols[2][0] = m.cols[0][2];
	ret.cols[0][1] = m.cols[1][0];
	ret.cols[1][1] = m.cols[1][1];
	ret.cols[2][1] = m.cols[1][2];
	return ret;
}
mat42f32 transposem24f32(mat24f32 m) {
	mat42f32 ret;
	ret.cols[0][0] = m.cols[0][0];
	ret.cols[1][0] = m.cols[0][1];
	ret.cols[2][0] = m.cols[0][2];
	ret.cols[3][0] = m.cols[0][3];
	ret.cols[0][1] = m.cols[1][0];
	ret.cols[1][1] = m.cols[1][1];
	ret.cols[2][1] = m.cols[1][2];
	ret.cols[3][1] = m.cols[1][3];
	return ret;
}
mat42f64 transposem24f64(mat24f64 m) {
	mat42f64 ret;
	ret.cols[0][0] = m.cols[0][0];
	ret.cols[1][0] = m.cols[0][1];
	ret.cols[2][0] = m.cols[0][2];
	ret.cols[3][0] = m.cols[0][3];
	ret.cols[0][1] = m.cols[1][0];
	ret.cols[1][1] = m.cols[1][1];
	ret.cols[2][1] = m.cols[1][2];
	ret.cols[3][1] = m.cols[1][3];
	return ret;
}
mat23f32 transposem32f32(mat32f32 m) {
	mat23f32 ret;
	ret.cols[0][0] = m.cols[0][0];
	ret.cols[1][0] = m.cols[0][1];
	ret.cols[0][1] = m.cols[1][0];
	ret.cols[1][1] = m.cols[1][1];
	ret.cols[0][2] = m.cols[2][0];
	ret.cols[1][2] = m.cols[2][1];
	return ret;
}
mat23f64 transposem32f64(mat32f64 m) {
	mat23f64 ret;
	ret.cols[0][0] = m.cols[0][0];
	ret.cols[1][0] = m.cols[0][1];
	ret.cols[0][1] = m.cols[1][0];
	ret.cols[1][1] = m.cols[1][1];
	ret.cols[0][2] = m.cols[2][0];
	ret.cols[1][2] = m.cols[2][1];
	return ret;
}
mat33f32 transposem33f32(mat33f32 m) {
	mat33f32 ret;
	ret.cols[0][0] = m.cols[0][0];
	ret.cols[1][0] = m.cols[0][1];
	ret.cols[2][0] = m.cols[0][2];
	ret.cols[0][1] = m.cols[1][0];
	ret.cols[1][1] = m.cols[1][1];
	ret.cols[2][1] = m.cols[1][2];
	ret.cols[0][2] = m.cols[2][0];
	ret.cols[1][2] = m.cols[2][1];
	ret.cols[2][2] = m.cols[2][2];
	return ret;
}
mat33f64 transposem33f64(mat33f64 m) {
	mat33f64 ret;
	ret.cols[0][0] = m.cols[0][0];
	ret.cols[1][0] = m.cols[0][1];
	ret.cols[2][0] = m.cols[0][2];
	ret.cols[0][1] = m.cols[1][0];
	ret.cols[1][1] = m.cols[1][1];
	ret.cols[2][1] = m.cols[1][2];
	ret.cols[0][2] = m.cols[2][0];
	ret.cols[1][2] = m.cols[2][1];
	ret.cols[2][2] = m.cols[2][2];
	return ret;
}
mat43f32 transposem34f32(mat34f32 m) {
	mat43f32 ret;
	ret.cols[0][0] = m.cols[0][0];
	ret.cols[1][0] = m.cols[0][1];
	ret.cols[2][0] = m.cols[0][2];
	ret.cols[3][0] = m.cols[0][3];
	ret.cols[0][1] = m.cols[1][0];
	ret.cols[1][1] = m.cols[1][1];
	ret.cols[2][1] = m.cols[1][2];
	ret.cols[3][1] = m.cols[1][3];
	ret.cols[0][2] = m.cols[2][0];
	ret.cols[1][2] = m.cols[2][1];
	ret.cols[2][2] = m.cols[2][2];
	ret.cols[3][2] = m.cols[2][3];
	return ret;
}
mat43f64 transposem34f64(mat34f64 m) {
	mat43f64 ret;
	ret.cols[0][0] = m.cols[0][0];
	ret.cols[1][0] = m.cols[0][1];
	ret.cols[2][0] = m.cols[0][2];
	ret.cols[3][0] = m.cols[0][3];
	ret.cols[0][1] = m.cols[1][0];
	ret.cols[1][1] = m.cols[1][1];
	ret.cols[2][1] = m.cols[1][2];
	ret.cols[3][1] = m.cols[1][3];
	ret.cols[0][2] = m.cols[2][0];
	ret.cols[1][2] = m.cols[2][1];
	ret.cols[2][2] = m.cols[2][2];
	ret.cols[3][2] = m.cols[2][3];
	return ret;
}
mat24f32 transposem42f32(mat42f32 m) {
	mat24f32 ret;
	ret.cols[0][0] = m.cols[0][0];
	ret.cols[1][0] = m.cols[0][1];
	ret.cols[0][1] = m.cols[1][0];
	ret.cols[1][1] = m.cols[1][1];
	ret.cols[0][2] = m.cols[2][0];
	ret.cols[1][2] = m.cols[2][1];
	ret.cols[0][3] = m.cols[3][0];
	ret.cols[1][3] = m.cols[3][1];
	return ret;
}
mat24f64 transposem42f64(mat42f64 m) {
	mat24f64 ret;
	ret.cols[0][0] = m.cols[0][0];
	ret.cols[1][0] = m.cols[0][1];
	ret.cols[0][1] = m.cols[1][0];
	ret.cols[1][1] = m.cols[1][1];
	ret.cols[0][2] = m.cols[2][0];
	ret.cols[1][2] = m.cols[2][1];
	ret.cols[0][3] = m.cols[3][0];
	ret.cols[1][3] = m.cols[3][1];
	return ret;
}
mat34f32 transposem43f32(mat43f32 m) {
	mat34f32 ret;
	ret.cols[0][0] = m.cols[0][0];
	ret.cols[1][0] = m.cols[0][1];
	ret.cols[2][0] = m.cols[0][2];
	ret.cols[0][1] = m.cols[1][0];
	ret.cols[1][1] = m.cols[1][1];
	ret.cols[2][1] = m.cols[1][2];
	ret.cols[0][2] = m.cols[2][0];
	ret.cols[1][2] = m.cols[2][1];
	ret.cols[2][2] = m.cols[2][2];
	ret.cols[0][3] = m.cols[3][0];
	ret.cols[1][3] = m.cols[3][1];
	ret.cols[2][3] = m.cols[3][2];
	return ret;
}
mat34f64 transposem43f64(mat43f64 m) {
	mat34f64 ret;
	ret.cols[0][0] = m.cols[0][0];
	ret.cols[1][0] = m.cols[0][1];
	ret.cols[2][0] = m.cols[0][2];
	ret.cols[0][1] = m.cols[1][0];
	ret.cols[1][1] = m.cols[1][1];
	ret.cols[2][1] = m.cols[1][2];
	ret.cols[0][2] = m.cols[2][0];
	ret.cols[1][2] = m.cols[2][1];
	ret.cols[2][2] = m.cols[2][2];
	ret.cols[0][3] = m.cols[3][0];
	ret.cols[1][3] = m.cols[3][1];
	ret.cols[2][3] = m.cols[3][2];
	return ret;
}
mat44f32 transposem44f32(mat44f32 m) {
	mat44f32 ret;
	ret.cols[0][0] = m.cols[0][0];
	ret.cols[1][0] = m.cols[0][1];
	ret.cols[2][0] = m.cols[0][2];
	ret.cols[3][0] = m.cols[0][3];
	ret.cols[0][1] = m.cols[1][0];
	ret.cols[1][1] = m.cols[1][1];
	ret.cols[2][1] = m.cols[1][2];
	ret.cols[3][1] = m.cols[1][3];
	ret.cols[0][2] = m.cols[2][0];
	ret.cols[1][2] = m.cols[2][1];
	ret.cols[2][2] = m.cols[2][2];
	ret.cols[3][2] = m.cols[2][3];
	ret.cols[0][3] = m.cols[3][0];
	ret.cols[1][3] = m.cols[3][1];
	ret.cols[2][3] = m.cols[3][2];
	ret.cols[3][3] = m.cols[3][3];
	return ret;
}
mat44f64 transposem44f64(mat44f64 m) {
	mat44f64 ret;
	ret.cols[0][0] = m.cols[0][0];
	ret.cols[1][0] = m.cols[0][1];
	ret.cols[2][0] = m.cols[0][2];
	ret.cols[3][0] = m.cols[0][3];
	ret.cols[0][1] = m.cols[1][0];
	ret.cols[1][1] = m.cols[1][1];
	ret.cols[2][1] = m.cols[1][2];
	ret.cols[3][1] = m.cols[1][3];
	ret.cols[0][2] = m.cols[2][0];
	ret.cols[1][2] = m.cols[2][1];
	ret.cols[2][2] = m.cols[2][2];
	ret.cols[3][2] = m.cols[2][3];
	ret.cols[0][3] = m.cols[3][0];
	ret.cols[1][3] = m.cols[3][1];
	ret.cols[2][3] = m.cols[3][2];
	ret.cols[3][3] = m.cols[3][3];
	return ret;
}

//
// returns a matrix from the outer product of vector 'a' and vector 'b'
mat22f32 outerproductv2v2f32(vec2f32 c, vec2f32 r) {
	mat22f32 ret;
	ret.cols[0][0] = c[0] * r[0];
	ret.cols[0][1] = c[0] * r[1];
	ret.cols[1][0] = c[1] * r[0];
	ret.cols[1][1] = c[1] * r[1];
	return ret;
}
mat22f64 outerproductv2v2f64(vec2f64 c, vec2f64 r) {
	mat22f64 ret;
	ret.cols[0][0] = c[0] * r[0];
	ret.cols[0][1] = c[0] * r[1];
	ret.cols[1][0] = c[1] * r[0];
	ret.cols[1][1] = c[1] * r[1];
	return ret;
}
mat23f32 outerproductv2v3f32(vec2f32 c, vec3f32 r) {
	mat23f32 ret;
	ret.cols[0][0] = c[0] * r[0];
	ret.cols[0][1] = c[0] * r[1];
	ret.cols[0][2] = c[0] * r[2];
	ret.cols[1][0] = c[1] * r[0];
	ret.cols[1][1] = c[1] * r[1];
	ret.cols[1][2] = c[1] * r[2];
	return ret;
}
mat23f64 outerproductv2v3f64(vec2f64 c, vec3f64 r) {
	mat23f64 ret;
	ret.cols[0][0] = c[0] * r[0];
	ret.cols[0][1] = c[0] * r[1];
	ret.cols[0][2] = c[0] * r[2];
	ret.cols[1][0] = c[1] * r[0];
	ret.cols[1][1] = c[1] * r[1];
	ret.cols[1][2] = c[1] * r[2];
	return ret;
}
mat24f32 outerproductv2v4f32(vec2f32 c, vec4f32 r) {
	mat24f32 ret;
	ret.cols[0][0] = c[0] * r[0];
	ret.cols[0][1] = c[0] * r[1];
	ret.cols[0][2] = c[0] * r[2];
	ret.cols[0][3] = c[0] * r[3];
	ret.cols[1][0] = c[1] * r[0];
	ret.cols[1][1] = c[1] * r[1];
	ret.cols[1][2] = c[1] * r[2];
	ret.cols[1][3] = c[1] * r[3];
	return ret;
}
mat24f64 outerproductv2v4f64(vec2f64 c, vec4f64 r) {
	mat24f64 ret;
	ret.cols[0][0] = c[0] * r[0];
	ret.cols[0][1] = c[0] * r[1];
	ret.cols[0][2] = c[0] * r[2];
	ret.cols[0][3] = c[0] * r[3];
	ret.cols[1][0] = c[1] * r[0];
	ret.cols[1][1] = c[1] * r[1];
	ret.cols[1][2] = c[1] * r[2];
	ret.cols[1][3] = c[1] * r[3];
	return ret;
}
mat32f32 outerproductv3v2f32(vec3f32 c, vec2f32 r) {
	mat32f32 ret;
	ret.cols[0][0] = c[0] * r[0];
	ret.cols[0][1] = c[0] * r[1];
	ret.cols[1][0] = c[1] * r[0];
	ret.cols[1][1] = c[1] * r[1];
	ret.cols[2][0] = c[2] * r[0];
	ret.cols[2][1] = c[2] * r[1];
	return ret;
}
mat32f64 outerproductv3v2f64(vec3f64 c, vec2f64 r) {
	mat32f64 ret;
	ret.cols[0][0] = c[0] * r[0];
	ret.cols[0][1] = c[0] * r[1];
	ret.cols[1][0] = c[1] * r[0];
	ret.cols[1][1] = c[1] * r[1];
	ret.cols[2][0] = c[2] * r[0];
	ret.cols[2][1] = c[2] * r[1];
	return ret;
}
mat33f32 outerproductv3v3f32(vec3f32 c, vec3f32 r) {
	mat33f32 ret;
	ret.cols[0][0] = c[0] * r[0];
	ret.cols[0][1] = c[0] * r[1];
	ret.cols[0][2] = c[0] * r[2];
	ret.cols[1][0] = c[1] * r[0];
	ret.cols[1][1] = c[1] * r[1];
	ret.cols[1][2] = c[1] * r[2];
	ret.cols[2][0] = c[2] * r[0];
	ret.cols[2][1] = c[2] * r[1];
	ret.cols[2][2] = c[2] * r[2];
	return ret;
}
mat33f64 outerproductv3v3f64(vec3f64 c, vec3f64 r) {
	mat33f64 ret;
	ret.cols[0][0] = c[0] * r[0];
	ret.cols[0][1] = c[0] * r[1];
	ret.cols[0][2] = c[0] * r[2];
	ret.cols[1][0] = c[1] * r[0];
	ret.cols[1][1] = c[1] * r[1];
	ret.cols[1][2] = c[1] * r[2];
	ret.cols[2][0] = c[2] * r[0];
	ret.cols[2][1] = c[2] * r[1];
	ret.cols[2][2] = c[2] * r[2];
	return ret;
}
mat34f32 outerproductv3v4f32(vec3f32 c, vec4f32 r) {
	mat34f32 ret;
	ret.cols[0][0] = c[0] * r[0];
	ret.cols[0][1] = c[0] * r[1];
	ret.cols[0][2] = c[0] * r[2];
	ret.cols[0][3] = c[0] * r[3];
	ret.cols[1][0] = c[1] * r[0];
	ret.cols[1][1] = c[1] * r[1];
	ret.cols[1][2] = c[1] * r[2];
	ret.cols[1][3] = c[1] * r[3];
	ret.cols[2][0] = c[2] * r[0];
	ret.cols[2][1] = c[2] * r[1];
	ret.cols[2][2] = c[2] * r[2];
	ret.cols[2][3] = c[2] * r[3];
	return ret;
}
mat34f64 outerproductv3v4f64(vec3f64 c, vec4f64 r) {
	mat34f64 ret;
	ret.cols[0][0] = c[0] * r[0];
	ret.cols[0][1] = c[0] * r[1];
	ret.cols[0][2] = c[0] * r[2];
	ret.cols[0][3] = c[0] * r[3];
	ret.cols[1][0] = c[1] * r[0];
	ret.cols[1][1] = c[1] * r[1];
	ret.cols[1][2] = c[1] * r[2];
	ret.cols[1][3] = c[1] * r[3];
	ret.cols[2][0] = c[2] * r[0];
	ret.cols[2][1] = c[2] * r[1];
	ret.cols[2][2] = c[2] * r[2];
	ret.cols[2][3] = c[2] * r[3];
	return ret;
}
mat42f32 outerproductv4v2f32(vec4f32 c, vec2f32 r) {
	mat42f32 ret;
	ret.cols[0][0] = c[0] * r[0];
	ret.cols[0][1] = c[0] * r[1];
	ret.cols[1][0] = c[1] * r[0];
	ret.cols[1][1] = c[1] * r[1];
	ret.cols[2][0] = c[2] * r[0];
	ret.cols[2][1] = c[2] * r[1];
	ret.cols[3][0] = c[3] * r[0];
	ret.cols[3][1] = c[3] * r[1];
	return ret;
}
mat42f64 outerproductv4v2f64(vec4f64 c, vec2f64 r) {
	mat42f64 ret;
	ret.cols[0][0] = c[0] * r[0];
	ret.cols[0][1] = c[0] * r[1];
	ret.cols[1][0] = c[1] * r[0];
	ret.cols[1][1] = c[1] * r[1];
	ret.cols[2][0] = c[2] * r[0];
	ret.cols[2][1] = c[2] * r[1];
	ret.cols[3][0] = c[3] * r[0];
	ret.cols[3][1] = c[3] * r[1];
	return ret;
}
mat43f32 outerproductv4v3f32(vec4f32 c, vec3f32 r) {
	mat43f32 ret;
	ret.cols[0][0] = c[0] * r[0];
	ret.cols[0][1] = c[0] * r[1];
	ret.cols[0][2] = c[0] * r[2];
	ret.cols[1][0] = c[1] * r[0];
	ret.cols[1][1] = c[1] * r[1];
	ret.cols[1][2] = c[1] * r[2];
	ret.cols[2][0] = c[2] * r[0];
	ret.cols[2][1] = c[2] * r[1];
	ret.cols[2][2] = c[2] * r[2];
	ret.cols[3][0] = c[3] * r[0];
	ret.cols[3][1] = c[3] * r[1];
	ret.cols[3][2] = c[3] * r[2];
	return ret;
}
mat43f64 outerproductv4v3f64(vec4f64 c, vec3f64 r) {
	mat43f64 ret;
	ret.cols[0][0] = c[0] * r[0];
	ret.cols[0][1] = c[0] * r[1];
	ret.cols[0][2] = c[0] * r[2];
	ret.cols[1][0] = c[1] * r[0];
	ret.cols[1][1] = c[1] * r[1];
	ret.cols[1][2] = c[1] * r[2];
	ret.cols[2][0] = c[2] * r[0];
	ret.cols[2][1] = c[2] * r[1];
	ret.cols[2][2] = c[2] * r[2];
	ret.cols[3][0] = c[3] * r[0];
	ret.cols[3][1] = c[3] * r[1];
	ret.cols[3][2] = c[3] * r[2];
	return ret;
}
mat44f32 outerproductv4v4f32(vec4f32 c, vec4f32 r) {
	mat44f32 ret;
	ret.cols[0][0] = c[0] * r[0];
	ret.cols[0][1] = c[0] * r[1];
	ret.cols[0][2] = c[0] * r[2];
	ret.cols[0][3] = c[0] * r[3];
	ret.cols[1][0] = c[1] * r[0];
	ret.cols[1][1] = c[1] * r[1];
	ret.cols[1][2] = c[1] * r[2];
	ret.cols[1][3] = c[1] * r[3];
	ret.cols[2][0] = c[2] * r[0];
	ret.cols[2][1] = c[2] * r[1];
	ret.cols[2][2] = c[2] * r[2];
	ret.cols[2][3] = c[2] * r[3];
	ret.cols[3][0] = c[3] * r[0];
	ret.cols[3][1] = c[3] * r[1];
	ret.cols[3][2] = c[3] * r[2];
	ret.cols[3][3] = c[3] * r[3];
	return ret;
}
mat44f64 outerproductv4v4f64(vec4f64 c, vec4f64 r) {
	mat44f64 ret;
	ret.cols[0][0] = c[0] * r[0];
	ret.cols[0][1] = c[0] * r[1];
	ret.cols[0][2] = c[0] * r[2];
	ret.cols[0][3] = c[0] * r[3];
	ret.cols[1][0] = c[1] * r[0];
	ret.cols[1][1] = c[1] * r[1];
	ret.cols[1][2] = c[1] * r[2];
	ret.cols[1][3] = c[1] * r[3];
	ret.cols[2][0] = c[2] * r[0];
	ret.cols[2][1] = c[2] * r[1];
	ret.cols[2][2] = c[2] * r[2];
	ret.cols[2][3] = c[2] * r[3];
	ret.cols[3][0] = c[3] * r[0];
	ret.cols[3][1] = c[3] * r[1];
	ret.cols[3][2] = c[3] * r[2];
	ret.cols[3][3] = c[3] * r[3];
	return ret;
}

//
// returns the determinant of matrix 'm'
float determinantm22f32(f32x2x2 m) {
	return m.cols[0][0] * m.cols[1][1] - m.cols[1][0] * m.cols[0][1];
}
double determinantm22f64(f64x2x2 m) {
	return m.cols[0][0] * m.cols[1][1] - m.cols[1][0] * m.cols[0][1];
}
float determinantm33f32(f32x3x3 m) {
	float s[3];
	s[0] = (m.cols[1][1] * m.cols[2][2]) - (m.cols[2][1] * m.cols[1][2]);
	s[1] = (m.cols[1][0] * m.cols[2][2]) - (m.cols[1][2] * m.cols[2][0]);
	s[2] = (m.cols[1][0] * m.cols[2][1]) - (m.cols[1][1] * m.cols[2][0]);
	float det = s[0] - s[1] + s[2];
	return det;
}
double determinantm33f64(f64x3x3 m) {
	double s[3];
	s[0] = (m.cols[1][1] * m.cols[2][2]) - (m.cols[2][1] * m.cols[1][2]);
	s[1] = (m.cols[1][0] * m.cols[2][2]) - (m.cols[1][2] * m.cols[2][0]);
	s[2] = (m.cols[1][0] * m.cols[2][1]) - (m.cols[1][1] * m.cols[2][0]);
	double det = s[0] - s[1] + s[2];
	return det;
}
float determinantm44f32(f32x4x4 m) {
	float s[6];
	float c[6];

	s[0] = m.cols[0][0]*m.cols[1][1] - m.cols[1][0]*m.cols[0][1];
	s[1] = m.cols[0][0]*m.cols[1][2] - m.cols[1][0]*m.cols[0][2];
	s[2] = m.cols[0][0]*m.cols[1][3] - m.cols[1][0]*m.cols[0][3];
	s[3] = m.cols[0][1]*m.cols[1][2] - m.cols[1][1]*m.cols[0][2];
	s[4] = m.cols[0][1]*m.cols[1][3] - m.cols[1][1]*m.cols[0][3];
	s[5] = m.cols[0][2]*m.cols[1][3] - m.cols[1][2]*m.cols[0][3];

	c[0] = m.cols[2][0]*m.cols[3][1] - m.cols[3][0]*m.cols[2][1];
	c[1] = m.cols[2][0]*m.cols[3][2] - m.cols[3][0]*m.cols[2][2];
	c[2] = m.cols[2][0]*m.cols[3][3] - m.cols[3][0]*m.cols[2][3];
	c[3] = m.cols[2][1]*m.cols[3][2] - m.cols[3][1]*m.cols[2][2];
	c[4] = m.cols[2][1]*m.cols[3][3] - m.cols[3][1]*m.cols[2][3];
	c[5] = m.cols[2][2]*m.cols[3][3] - m.cols[3][2]*m.cols[2][3];

	float det = s[0]*c[5]-s[1]*c[4]+s[2]*c[3]+s[3]*c[2]-s[4]*c[1]+s[5]*c[0];
	return det;
}
double determinantm44f64(f64x4x4 m) {
	double s[6];
	double c[6];

	s[0] = m.cols[0][0]*m.cols[1][1] - m.cols[1][0]*m.cols[0][1];
	s[1] = m.cols[0][0]*m.cols[1][2] - m.cols[1][0]*m.cols[0][2];
	s[2] = m.cols[0][0]*m.cols[1][3] - m.cols[1][0]*m.cols[0][3];
	s[3] = m.cols[0][1]*m.cols[1][2] - m.cols[1][1]*m.cols[0][2];
	s[4] = m.cols[0][1]*m.cols[1][3] - m.cols[1][1]*m.cols[0][3];
	s[5] = m.cols[0][2]*m.cols[1][3] - m.cols[1][2]*m.cols[0][3];

	c[0] = m.cols[2][0]*m.cols[3][1] - m.cols[3][0]*m.cols[2][1];
	c[1] = m.cols[2][0]*m.cols[3][2] - m.cols[3][0]*m.cols[2][2];
	c[2] = m.cols[2][0]*m.cols[3][3] - m.cols[3][0]*m.cols[2][3];
	c[3] = m.cols[2][1]*m.cols[3][2] - m.cols[3][1]*m.cols[2][2];
	c[4] = m.cols[2][1]*m.cols[3][3] - m.cols[3][1]*m.cols[2][3];
	c[5] = m.cols[2][2]*m.cols[3][3] - m.cols[3][2]*m.cols[2][3];

	double det = s[0]*c[5]-s[1]*c[4]+s[2]*c[3]+s[3]*c[2]-s[4]*c[1]+s[5]*c[0];
	return det;
}

//
// returns the inverse of matrix 'm'
f32x2x2 inversem22f32(f32x2x2 m) {
	float inv_det = 1.0 / determinantm22f32(m);
	f32x2x2 ret;
	ret.cols[0][0] = m.cols[1][1] * inv_det;
	ret.cols[0][1] = -m.cols[0][1] * inv_det;
	
	ret.cols[1][0] = -m.cols[1][0] * inv_det;
	ret.cols[1][1] = m.cols[0][0] * inv_det;
	return ret;
}
f64x2x2 inversem22f64(f64x2x2 m) {
	double inv_det = 1.0 / determinantm22f64(m);
	f64x2x2 ret;
	ret.cols[0][0] = m.cols[1][1] * inv_det;
	ret.cols[0][1] = -m.cols[0][1] * inv_det;
	
	ret.cols[1][0] = -m.cols[1][0] * inv_det;
	ret.cols[1][1] = m.cols[0][0] * inv_det;
	return ret;
}
f32x3x3 inversem33f32(f32x3x3 m) {
	float s[3];
	s[0] = (m.cols[1][1] * m.cols[2][2]) - (m.cols[2][1] * m.cols[1][2]);
	s[1] = (m.cols[1][0] * m.cols[2][2]) - (m.cols[1][2] * m.cols[2][0]);
	s[2] = (m.cols[1][0] * m.cols[2][1]) - (m.cols[1][1] * m.cols[2][0]);
	float det = s[0] - s[1] + s[2];
	float inv_det = 1.0 / det;
	f32x3x3 ret;
	ret.cols[0][0] = s[0] * inv_det;
	ret.cols[0][1] = (m.cols[0][2] * m.cols[2][1] - m.cols[0][1] * m.cols[2][2]) * inv_det;
	ret.cols[0][2] = (m.cols[0][1] * m.cols[1][2] - m.cols[0][2] * m.cols[1][1]) * inv_det;
	
	ret.cols[1][0] = -s[1] * inv_det;
	ret.cols[1][1] = (m.cols[0][0] * m.cols[2][2] - m.cols[0][2] * m.cols[2][0]) * inv_det;
	ret.cols[1][2] = (m.cols[1][0] * m.cols[0][2] - m.cols[0][0] * m.cols[1][2]) * inv_det;
	
	ret.cols[2][0] = s[2] * inv_det;
	ret.cols[2][1] = (m.cols[2][0] * m.cols[0][1] - m.cols[0][0] * m.cols[2][1]) * inv_det;
	ret.cols[2][2] = (m.cols[0][0] * m.cols[1][1] - m.cols[1][0] * m.cols[0][1]) * inv_det;
	return ret;
}
f64x3x3 inversem33f64(f64x3x3 m) {
	double s[3];
	s[0] = (m.cols[1][1] * m.cols[2][2]) - (m.cols[2][1] * m.cols[1][2]);
	s[1] = (m.cols[1][0] * m.cols[2][2]) - (m.cols[1][2] * m.cols[2][0]);
	s[2] = (m.cols[1][0] * m.cols[2][1]) - (m.cols[1][1] * m.cols[2][0]);
	double det = s[0] - s[1] + s[2];
	double inv_det = 1.0 / det;
	f64x3x3 ret;
	ret.cols[0][0] = s[0] * inv_det;
	ret.cols[0][1] = (m.cols[0][2] * m.cols[2][1] - m.cols[0][1] * m.cols[2][2]) * inv_det;
	ret.cols[0][2] = (m.cols[0][1] * m.cols[1][2] - m.cols[0][2] * m.cols[1][1]) * inv_det;
	
	ret.cols[1][0] = -s[1] * inv_det;
	ret.cols[1][1] = (m.cols[0][0] * m.cols[2][2] - m.cols[0][2] * m.cols[2][0]) * inv_det;
	ret.cols[1][2] = (m.cols[1][0] * m.cols[0][2] - m.cols[0][0] * m.cols[1][2]) * inv_det;
	
	ret.cols[2][0] = s[2] * inv_det;
	ret.cols[2][1] = (m.cols[2][0] * m.cols[0][1] - m.cols[0][0] * m.cols[2][1]) * inv_det;
	ret.cols[2][2] = (m.cols[0][0] * m.cols[1][1] - m.cols[1][0] * m.cols[0][1]) * inv_det;
	return ret;
}
f32x4x4 inversem44f32(f32x4x4 m) {
	float s[6];
	float c[6];

	s[0] = m.cols[0][0]*m.cols[1][1] - m.cols[1][0]*m.cols[0][1];
	s[1] = m.cols[0][0]*m.cols[1][2] - m.cols[1][0]*m.cols[0][2];
	s[2] = m.cols[0][0]*m.cols[1][3] - m.cols[1][0]*m.cols[0][3];
	s[3] = m.cols[0][1]*m.cols[1][2] - m.cols[1][1]*m.cols[0][2];
	s[4] = m.cols[0][1]*m.cols[1][3] - m.cols[1][1]*m.cols[0][3];
	s[5] = m.cols[0][2]*m.cols[1][3] - m.cols[1][2]*m.cols[0][3];

	c[0] = m.cols[2][0]*m.cols[3][1] - m.cols[3][0]*m.cols[2][1];
	c[1] = m.cols[2][0]*m.cols[3][2] - m.cols[3][0]*m.cols[2][2];
	c[2] = m.cols[2][0]*m.cols[3][3] - m.cols[3][0]*m.cols[2][3];
	c[3] = m.cols[2][1]*m.cols[3][2] - m.cols[3][1]*m.cols[2][2];
	c[4] = m.cols[2][1]*m.cols[3][3] - m.cols[3][1]*m.cols[2][3];
	c[5] = m.cols[2][2]*m.cols[3][3] - m.cols[3][2]*m.cols[2][3];

	float det = s[0]*c[5]-s[1]*c[4]+s[2]*c[3]+s[3]*c[2]-s[4]*c[1]+s[5]*c[0];
	float inv_det = 1.0 / det;
	f32x4x4 ret;
	ret.cols[0][0] = ( m.cols[1][1] * c[5] - m.cols[1][2] * c[4] + m.cols[1][3] * c[3]) * inv_det;
	ret.cols[0][1] = (-m.cols[0][1] * c[5] + m.cols[0][2] * c[4] - m.cols[0][3] * c[3]) * inv_det;
	ret.cols[0][2] = ( m.cols[3][1] * s[5] - m.cols[3][2] * s[4] + m.cols[3][3] * s[3]) * inv_det;
	ret.cols[0][3] = (-m.cols[2][1] * s[5] + m.cols[2][2] * s[4] - m.cols[2][3] * s[3]) * inv_det;
	
	ret.cols[1][0] = (-m.cols[1][0] * c[5] + m.cols[1][2] * c[2] - m.cols[1][3] * c[1]) * inv_det;
	ret.cols[1][1] = ( m.cols[0][0] * c[5] - m.cols[0][2] * c[2] + m.cols[0][3] * c[1]) * inv_det;
	ret.cols[1][2] = (-m.cols[3][0] * s[5] + m.cols[3][2] * s[2] - m.cols[3][3] * s[1]) * inv_det;
	ret.cols[1][3] = ( m.cols[2][0] * s[5] - m.cols[2][2] * s[2] + m.cols[2][3] * s[1]) * inv_det;
	
	ret.cols[2][0] = ( m.cols[1][0] * c[4] - m.cols[1][1] * c[2] + m.cols[1][3] * c[0]) * inv_det;
	ret.cols[2][1] = (-m.cols[0][0] * c[4] + m.cols[0][1] * c[2] - m.cols[0][3] * c[0]) * inv_det;
	ret.cols[2][2] = ( m.cols[3][0] * s[4] - m.cols[3][1] * s[2] + m.cols[3][3] * s[0]) * inv_det;
	ret.cols[2][3] = (-m.cols[2][0] * s[4] + m.cols[2][1] * s[2] - m.cols[2][3] * s[0]) * inv_det;
	
	ret.cols[3][0] = (-m.cols[1][0] * c[3] + m.cols[1][1] * c[1] - m.cols[1][2] * c[0]) * inv_det;
	ret.cols[3][1] = ( m.cols[0][0] * c[3] - m.cols[0][1] * c[1] + m.cols[0][2] * c[0]) * inv_det;
	ret.cols[3][2] = (-m.cols[3][0] * s[3] + m.cols[3][1] * s[1] - m.cols[3][2] * s[0]) * inv_det;
	ret.cols[3][3] = ( m.cols[2][0] * s[3] - m.cols[2][1] * s[1] + m.cols[2][2] * s[0]) * inv_det;
	return ret;
}
f64x4x4 inversem44f64(f64x4x4 m) {
	double s[6];
	double c[6];

	s[0] = m.cols[0][0]*m.cols[1][1] - m.cols[1][0]*m.cols[0][1];
	s[1] = m.cols[0][0]*m.cols[1][2] - m.cols[1][0]*m.cols[0][2];
	s[2] = m.cols[0][0]*m.cols[1][3] - m.cols[1][0]*m.cols[0][3];
	s[3] = m.cols[0][1]*m.cols[1][2] - m.cols[1][1]*m.cols[0][2];
	s[4] = m.cols[0][1]*m.cols[1][3] - m.cols[1][1]*m.cols[0][3];
	s[5] = m.cols[0][2]*m.cols[1][3] - m.cols[1][2]*m.cols[0][3];

	c[0] = m.cols[2][0]*m.cols[3][1] - m.cols[3][0]*m.cols[2][1];
	c[1] = m.cols[2][0]*m.cols[3][2] - m.cols[3][0]*m.cols[2][2];
	c[2] = m.cols[2][0]*m.cols[3][3] - m.cols[3][0]*m.cols[2][3];
	c[3] = m.cols[2][1]*m.cols[3][2] - m.cols[3][1]*m.cols[2][2];
	c[4] = m.cols[2][1]*m.cols[3][3] - m.cols[3][1]*m.cols[2][3];
	c[5] = m.cols[2][2]*m.cols[3][3] - m.cols[3][2]*m.cols[2][3];

	double det = s[0]*c[5]-s[1]*c[4]+s[2]*c[3]+s[3]*c[2]-s[4]*c[1]+s[5]*c[0];
	double inv_det = 1.0 / det;
	f64x4x4 ret;
	ret.cols[0][0] = ( m.cols[1][1] * c[5] - m.cols[1][2] * c[4] + m.cols[1][3] * c[3]) * inv_det;
	ret.cols[0][1] = (-m.cols[0][1] * c[5] + m.cols[0][2] * c[4] - m.cols[0][3] * c[3]) * inv_det;
	ret.cols[0][2] = ( m.cols[3][1] * s[5] - m.cols[3][2] * s[4] + m.cols[3][3] * s[3]) * inv_det;
	ret.cols[0][3] = (-m.cols[2][1] * s[5] + m.cols[2][2] * s[4] - m.cols[2][3] * s[3]) * inv_det;
	
	ret.cols[1][0] = (-m.cols[1][0] * c[5] + m.cols[1][2] * c[2] - m.cols[1][3] * c[1]) * inv_det;
	ret.cols[1][1] = ( m.cols[0][0] * c[5] - m.cols[0][2] * c[2] + m.cols[0][3] * c[1]) * inv_det;
	ret.cols[1][2] = (-m.cols[3][0] * s[5] + m.cols[3][2] * s[2] - m.cols[3][3] * s[1]) * inv_det;
	ret.cols[1][3] = ( m.cols[2][0] * s[5] - m.cols[2][2] * s[2] + m.cols[2][3] * s[1]) * inv_det;
	
	ret.cols[2][0] = ( m.cols[1][0] * c[4] - m.cols[1][1] * c[2] + m.cols[1][3] * c[0]) * inv_det;
	ret.cols[2][1] = (-m.cols[0][0] * c[4] + m.cols[0][1] * c[2] - m.cols[0][3] * c[0]) * inv_det;
	ret.cols[2][2] = ( m.cols[3][0] * s[4] - m.cols[3][1] * s[2] + m.cols[3][3] * s[0]) * inv_det;
	ret.cols[2][3] = (-m.cols[2][0] * s[4] + m.cols[2][1] * s[2] - m.cols[2][3] * s[0]) * inv_det;
	
	ret.cols[3][0] = (-m.cols[1][0] * c[3] + m.cols[1][1] * c[1] - m.cols[1][2] * c[0]) * inv_det;
	ret.cols[3][1] = ( m.cols[0][0] * c[3] - m.cols[0][1] * c[1] + m.cols[0][2] * c[0]) * inv_det;
	ret.cols[3][2] = (-m.cols[3][0] * s[3] + m.cols[3][1] * s[1] - m.cols[3][2] * s[0]) * inv_det;
	ret.cols[3][3] = ( m.cols[2][0] * s[3] - m.cols[2][1] * s[1] + m.cols[2][2] * s[0]) * inv_det;
	return ret;
}
