
const char* hcc_resource_access_mode_strings[HCC_RESOURCE_ACCESS_MODE_COUNT] = {
	[HCC_RESOURCE_ACCESS_MODE_READ_ONLY] = "HCC_RESOURCE_ACCESS_MODE_READ_ONLY",
	[HCC_RESOURCE_ACCESS_MODE_WRITE_ONLY] = "HCC_RESOURCE_ACCESS_MODE_WRITE_ONLY",
	[HCC_RESOURCE_ACCESS_MODE_READ_WRITE] = "HCC_RESOURCE_ACCESS_MODE_READ_WRITE",
	[HCC_RESOURCE_ACCESS_MODE_SAMPLE] = "HCC_RESOURCE_ACCESS_MODE_SAMPLE",
};

const char* hcc_shader_stage_strings[HCC_SHADER_STAGE_COUNT] = {
	[HCC_SHADER_STAGE_NONE] = "HCC_SHADER_STAGE_NONE",
	[HCC_SHADER_STAGE_VERTEX] = "HCC_SHADER_STAGE_VERTEX",
	[HCC_SHADER_STAGE_PIXEL] = "HCC_SHADER_STAGE_PIXEL",
	[HCC_SHADER_STAGE_COMPUTE] = "HCC_SHADER_STAGE_COMPUTE",
	[HCC_SHADER_STAGE_MESH_TASK] = "HCC_SHADER_STAGE_MESH_TASK",
	[HCC_SHADER_STAGE_MESH] = "HCC_SHADER_STAGE_MESH",
};

const char* hcc_resource_type_strings[HCC_RESOURCE_TYPE_COUNT] = {
	[HCC_RESOURCE_TYPE_BUFFER] = "HCC_RESOURCE_TYPE_BUFFER",
	[HCC_RESOURCE_TYPE_TEXTURE_1D] = "HCC_RESOURCE_TYPE_TEXTURE_1D",
	[HCC_RESOURCE_TYPE_TEXTURE_1D_ARRAY] = "HCC_RESOURCE_TYPE_TEXTURE_1D_ARRAY",
	[HCC_RESOURCE_TYPE_TEXTURE_2D] = "HCC_RESOURCE_TYPE_TEXTURE_2D",
	[HCC_RESOURCE_TYPE_TEXTURE_2D_MS] = "HCC_RESOURCE_TYPE_TEXTURE_2D_MS",
	[HCC_RESOURCE_TYPE_TEXTURE_2D_ARRAY] = "HCC_RESOURCE_TYPE_TEXTURE_2D_ARRAY",
	[HCC_RESOURCE_TYPE_TEXTURE_2D_MS_ARRAY] = "HCC_RESOURCE_TYPE_TEXTURE_2D_MS_ARRAY",
	[HCC_RESOURCE_TYPE_TEXTURE_2D_CUBE] = "HCC_RESOURCE_TYPE_TEXTURE_2D_CUBE",
	[HCC_RESOURCE_TYPE_TEXTURE_2D_CUBE_ARRAY] = "HCC_RESOURCE_TYPE_TEXTURE_2D_CUBE_ARRAY",
	[HCC_RESOURCE_TYPE_TEXTURE_3D] = "HCC_RESOURCE_TYPE_TEXTURE_3D",
	[HCC_RESOURCE_TYPE_SAMPLER] = "HCC_RESOURCE_TYPE_SAMPLER",
};

